### ISSUE TITLE
doesn't work on windows

### ISSUE THREAD

**Issue by neeasade** [alphapapa/magit-todos#10]
missing the `nice` command -- maybe just note that windows isn't supported in the README due to that.

**Comment by alphapapa** [comment]
I guess you're not using Cygwin then.  :)  Well, it's easy enough to make `nice` optional, but I can't guarantee it will work on Windows after that.  I'll let you know when to test again.  Thanks.

**Comment by alphapapa** [comment]
You can now disable nice in the customization.  Please let me know if it works for you.  If not, you should be able to use the built-in scanner.
