### ISSUE TITLE
Default rg choice searches all files including untracked

### ISSUE THREAD

**Issue by pengwyn** [alphapapa/magit-todos#100]
This is a problem that often bites me when I have a small number of source files, but a large number of compiled/support libraries in the same directory. Makes it both slow to identify all of the todos in my source files and often errors arise, such as "line too long" in untracked files.

I got around this by setting my default scanner to git-grep.

I thought I should submit a pull request that allows the rg scanner to only look at tracked files. However, this didn't turn out to be easy. In fact, I can't figure out how to make rg only look at a particular list of files. Hence, I'm leaving this issue in the hope that someone else has an idea!

**Comment by alphapapa** [comment]
AFAIK ripgrep respects `.gitignore` files, but I guess to only search tracked files would require it to query git somehow, which I wouldn't expect ripgrep to do.

So I guess you could write an Elisp function or a shell command to pass a list of files from git to ripgrep, but that might not be worth the trouble.  All that extra work might defeat any performance advantage ripgrep might have.

Is the git-grep scanner sufficient for this use case?

**Comment by pengwyn** [comment]
I've only used it for a little bit now but it has worked fine so far. So this is not so much an issue raised about functionality (which works great by the way!), but just how the behaviour I expected didn't match up with what was happening. I found it confusing because this is magit-todos, so it was unexpected to me that the search included files that are not tracked by git.

My first assumption was that there would be a customizable option that would force all scanners (ripgrep, ag, grep, etc...) to search either tracked files or all files, with the default being only tracked files.

I think I finally found that ripgrep accepts a list of files only by listing them in its argument list, which makes it a little cumbersome. However, I might be able to wrangle something together with `git ls-files | xargs ripgrep`.

But this depends on whether you'd like to change the default behaviour of magit-todos, or keep it as it currently acts. What's your thoughts on that?

**Comment by alphapapa** [comment]
> But this depends on whether you'd like to change the default behaviour of magit-todos, or keep it as it currently acts. What's your thoughts on that?

I don't know.  You're the first user to say anything about this issue, so I guess it doesn't affect many users.  And using git-grep to scan seems to solve it.  So unless it's really necessary to use ripgrep in this way, and unless the performance impact is negligible, it probably wouldn't be worth doing, IMO.

**Comment by pengwyn** [comment]
Yeap fair enough, I'll leave it alone then. Thanks for your comments!
