### ISSUE TITLE
Do not show submodule notes

### ISSUE THREAD

**Issue by matsievskiysv** [alphapapa/magit-todos#104]
If repo have submodules, it's usually not desired to have their notes displayed with repo notes.
 It would be great if magit-todos could optionally add submodule paths from `.gitmodules` to the list of excluded globs.

**Comment by alphapapa** [comment]
That could be helpful.  Are there any Magit functions that return the paths to submodules?

**Comment by matsievskiysv** [comment]
I think `magit-list-module-paths` is the one.
