### ISSUE TITLE
Line truncation customization

### ISSUE THREAD

**Issue by matsievskiysv** [alphapapa/magit-todos#105]
Java based languages have directory structures with many subfolders. Because of that paths may be very long and TODO notes may be truncated. It would be great if there was a file path truncation customization options. Maybe optionally replace full relative file path with just a filename or something like that.

**Comment by alphapapa** [comment]
That could be useful.  I probably wouldn't use such an option myself, so I probably won't work on this soon.  Patches welcome, of course.  :)

**Comment by alphapapa** [comment]
Solved in https://github.com/alphapapa/magit-todos/commit/cb06a9e54154d132e9129ca20cfd9608123a3c78.
