### ISSUE TITLE
Feature request: avoid rescans in certain magit workflows?

### ISSUE THREAD

**Issue by zhaojiangbin** [alphapapa/magit-todos#11]
First of all, impressive improvement to the performance. In one of my repos, in the ~1100 source code files, the section shows up folded almost instantaneously with 84 items found by `rg`.

But in certain workflows, I feel the rescans are unnecessarily too frequent. For example, I often review code changes in the magit-status buffer, stage or unstage them, file by file, or even hunk by hunk. Every time I stage or unstage a change, I notice the TODOs section is refreshed. 

In workflows where the TODO items don't change, such rescans are a waste of CPU cycles, and battery power when my laptop is not plugged.

Would it be possible to have an option that, if enabled, the items are scanned only when:

1.  the magit-status buffer is created, or
2. the buffer is refreshed explicitly by pressing 'g'.

**Comment by alphapapa** [comment]
Hi,

Glad to hear it's working better now.

Yes, the section does get recreated often, especially you use `magit-auto-revert-mode` like I do.  I would like to improve that, but I'm not sure of the best way to do so.  I want to avoid doing too many hacks on top of Magit's own code.

Well, I guess the simplest way would be to use `memoize` to set a timeout on the code, and that would prevent it from updating the list more often than whatever frequency the user sets.  That would present stale data occasionally.  It seems like it should be possible to have a force-update argument, but I'm not sure how to pass that through Magit to the underlying function.

Looking at `magit-refresh`, maybe something could be done in the `magit-pre-refresh-hook’ and `magit-post-refresh-hook’...

**Comment by zhaojiangbin** [comment]
Just tried it in another repo with about 6000 source code files. The scan and inserting the section obviously take a few seconds to finish. There are about 1100 items, ("TODO", "XXX", and "FIXME"), found in this repo (I know, too much technical debt here).

Pressing <kbd>g</kbd> in the magit-status buffer makes Emacs freeze for a fraction of second. Short but it's definitely there. And before the section finishes insertion, moving the point in the magit-status buffer feels sluggish.

To see whether it's the running of the external tool, `rg` in this case, or the insertion of the items that is taking more time, I modified the keyword lists so that there was only one hit in the whole repo. I can tell that it's noticeably faster with less items.

**Comment by alphapapa** [comment]
Yes, it does take time to parse the output from `rg` and insert thousands of Magit sections.  We could try profiling, but I doubt there's much room for improvement there.

**Comment by zhaojiangbin** [comment]
I agree that the real fix will still be to not rescan unless it's called for explicitly.

**Comment by alphapapa** [comment]
It seems like doing manual scans is not too difficult: when `magit-todos-mode` is disabled, evaluating `(magit-todos--insert-items)` from the status buffer inserts the section as usual.  However, that means it won't be inserted again when the status buffer is refreshed.  I guess we could cache the items ourselves and let the section be recreated each time...

**Comment by alphapapa** [comment]
Ok, I pushed a branch which I think implements this fairly well.  The list can be updated automatically, as it is now, or manually by calling `magit-todos-update`, or when a number of seconds have passed since the last scan.  When not updating automatically, items are cached and the section is reinserted instantly.

I'm not sure what key to bind for updating the section manually.  Do you have any ideas?

Please let me know how it works for you.  Thanks!

**Comment by zhaojiangbin** [comment]
Very nice to have this coming.

Some initial thoughts after using the Manual option for less than an hour:

- The "(update manually)" reminder is nice. It would be useful to keep it in some way even after `magit-todos-update` runs. When magit by default auto refreshes almost everything else, having this section refreshed manually has the risk of serving staled info. A prominent reminder, or warning if you will, would be necessary, IMO.
- Manual updates appear to be slower somehow. This could be just perception or within the margin of error as I only compared it to auto updates a few times in one small repo, by eyeballing. Having browsed the changes, I see no apparent reason that manual updates need to be slower. I will keep an eye on it.
- What would be a good use case for the 'every N seconds' option? I haven't tried it myself. Will it run after N seconds even the magit-status buffer is not shown in any window? Will it keep running every N seconds?

> I'm not sure what key to bind for updating the section manually.

Yeah difficult question. Magit itself has taken almost everthing from 'a' to 'z', upper and lower. Perhaps <kbd>C-t</kbd> by default and let the end user to customize. 😄

I wish `magit-refresh` checks `called-interactively-p` and passes the result onto, say, `magit-status-refresh-buffer`. Then it will be possible to have `magit-todos--insert-items` run only when  <kbd>g</kbd> is pressed in the status buffer. That'd be perfect for me.

Another option I was thinking is to define a popup for the TODOs section. Calling `magit-todos-update` would then be a popup action. Such popup can have a lot more uses, too. But I am worried that magit popups are to be deprecated, as said by the [Magit Popup package manual](https://magit.vc/manual/magit-popup.html):

> This library does not depend on any other Magit libraries and it is distributed as a separate package, which makes it possible to use it in packages that are not related to Magit. But keep in mind that it will be deprecated eventually.

**Comment by alphapapa** [comment]
> The "(update manually)" reminder is nice. It would be useful to keep it in some way even after magit-todos-update runs. When magit by default auto refreshes almost everything else, having this section refreshed manually has the risk of serving staled info. A prominent reminder, or warning if you will, would be necessary, IMO.

Good idea.

> Manual updates appear to be slower somehow. This could be just perception or within the margin of error as I only compared it to auto updates a few times in one small repo, by eyeballing. Having browsed the changes, I see no apparent reason that manual updates need to be slower. I will keep an eye on it.

It's calling the same code, so it shouldn't be slower.

> What would be a good use case for the 'every N seconds' option? I haven't tried it myself. Will it run after N seconds even the magit-status buffer is not shown in any window? Will it keep running every N seconds?

I need to clarify the documentation for that.  What it does is cache the last scan for N seconds, so if the Magit status buffer is refreshed within N seconds, it uses the cached items.  IOW, it scans for items no more than every N seconds, and only when the status buffer is refreshed.

> Yeah difficult question. Magit itself has taken almost everthing from 'a' to 'z', upper and lower. Perhaps C-t by default and let the end user to customize.

What if we use the existing `jT` jump-to-todos-section bind to also update the section when that is pressed?

> I wish magit-refresh checks called-interactively-p and passes the result onto, say, magit-status-refresh-buffer. Then it will be possible to have magit-todos--insert-items run only when g is pressed in the status buffer. That'd be perfect for me.

Yes, some way to pass interactive-p and prefixes to functions called in the add-section-hook would be ideal.  Would you be interested in proposing a patch to Magit to add that?  I think Jonas might be open to the idea, because I don't think it would interfere with anything.

> Another option I was thinking is to define a popup for the TODOs section. Calling magit-todos-update would then be a popup action. Such popup can have a lot more uses, too. But I am worried that magit popups are to be deprecated, as said by the Magit Popup package manual:

That's an interesting idea, I hadn't thought of that.  I think what he means is that he is planning to rewrite the popup library eventually--I can't recall if he's already started work on that, but I've read some of the PRs planning it.  So we could certainly do that, but it just means that we might eventually have to port it to the new library.

What ideas were you thinking of for a popup?  I guess it could toggle the grouping and sorting options, maybe add/remove keywords, etc.  Do you think that would be useful?  Perhaps it could optionally store the changed settings to dir-local variables as well.

**Comment by alphapapa** [comment]
Is this docstring easier to understand?  Please let me know if it needs more work.

```el
(defcustom magit-todos-update t
  "When or how often to scan for to-dos.
When set to manual updates, the list can be updated with the
`magit-todos-update' command.  When caching is enabled, scan for
items whenever the Magit status buffer is refreshed and at least
N seconds have passed since the last scan; otherwise, use cached
items."
  :type '(choice (const :tag "Automatically, when the Magit status buffer is refreshed" t)
                 (integer :tag "Automatically, but cache items for N seconds")
                 (const :tag "Manually" nil)))
```

**Comment by alphapapa** [comment]
> The "(update manually)" reminder is nice. It would be useful to keep it in some way even after magit-todos-update runs. When magit by default auto refreshes almost everything else, having this section refreshed manually has the risk of serving staled info. A prominent reminder, or warning if you will, would be necessary, IMO.

The reminder is now always present when using manual updates.

I've tested with all 3 modes, automatic, manual, and cached, and it seems to work properly now.  Please let me know what you think.  Thank you for all your feedback.

**Comment by alphapapa** [comment]
I went ahead and merged it, but please let me know if you have any more feedback.  Thanks.

**Comment by alphapapa** [comment]
Discovered a couple minor issues after doing that.  Should be fixed on `master` now.  Please let me know what you think.

**Comment by alphapapa** [comment]
Aaaaand one more time.  I tried to make the logic as smart and convenient as possible.  Hopefully this does it.  :)

**Comment by alphapapa** [comment]
I keep finding little things to clarify!  I think this does it.  Let me know if you find anything else!

**Comment by zhaojiangbin** [comment]
> Is this docstring easier to understand? Please let me know if it needs more work.

It's clear to me now.

> What if we use the existing jT jump-to-todos-section bind to also update the section when that is pressed?

That would be even better for my taste. Even if we can get interactive-p from `magit-refresh`, there are still cases where I don't care about the TODOs until I really want to review them. Then I just press <kbd>jT</kbd> to update section and jump to it. Perfect.

> Yes, some way to pass interactive-p and prefixes to functions called in the add-section-hook would be ideal. Would you be interested in proposing a patch to Magit to add that? I think Jonas might be open to the idea, because I don't think it would interfere with anything.

I am not very familiar with the magit code. I will give it a try. So it will be to replace `run-hooks` with `run-hooks-with-args` to pass the info? Will that force the existing hook functions to change?

> What ideas were you thinking of for a popup? I guess it could toggle the grouping and sorting options, maybe add/remove keywords, etc. Do you think that would be useful? Perhaps it could optionally store the changed settings to dir-local variables as well.

They are all useful in a magit popup. I love magit popups because they are easier and quicker to use than the Emacs customization UI.

It would be great if changed settings can be saved to dir-local variables. That will allow per-user, per-repo settings. Very useful for users who have multiple, large repos to work on concurrently.

There are a few more things I were thinking:
- filter by directories: In large repos, developers usually have focus on certain parts organized as directories. It'd be nice to limit the scan to those directories. Yet it's still needed occasionally to see TODO/FIXME items in other parts. A magit popup will make it much easier to change such filtering on the fly. This can also speed up scans if the filter is turned into globs for the external tools.
- filter by owners: In large repos with multiple developers, the TODO/FIXME items often are followed by a name to indicate ownership. A developer usually cares about his/her own items. A team leader cares about items of his/her team members, etc.

Do you like a feature request issue for this magit popup idea?

**Comment by zhaojiangbin** [comment]
> I keep finding little things to clarify! I think this does it. Let me know if you find anything else!

Manual update and <kbd>jT</kbd> all work as expected.

But I am getting 'user-error: There is no thing at point that could be visited' when pressing <kbd>RET</kbd> on any item. Pressing <kbd>SPC</kbd> is also not working. It's prompting for selecting a commit to show.

Tested ceeec11378166c399a909e584dffef40858dac35, with the minimal configuration as below:
```
(use-package magit-todos
  ;; :ensure t
  :load-path "~/CodeWorks/emacs/magit-todos"
  :commands (magit-todos-mode)
  :hook (magit-mode . magit-todos-mode)
  :config
  (setq magit-todos-recursive t
        magit-todos-depth 100
        magit-todos-update t))
```

**Comment by alphapapa** [comment]
> That would be even better for my taste. Even if we can get interactive-p from magit-refresh, there are still cases where I don't care about the TODOs until I really want to review them. Then I just press jT to update section and jump to it. Perfect.

It should now work exactly as you described.  Please let me know if you find any problems.

> I am not very familiar with the magit code. I will give it a try. So it will be to replace run-hooks with run-hooks-with-args to pass the info? Will that force the existing hook functions to change?

I don't think it would be quite that simple, and yes, I think it would likely break the hook functions, but I haven't looked at the code myself.  If you're interested, I encourage you to go for it, but it will probably be more complicated than we expect.  You might want to ask Jonas what he thinks about the idea before doing too much work on it, because the way we are manipulating sections after the status buffer is refreshed is unintended and unsupported, so he might not want to make those changes.

> Do you like a feature request issue for this magit popup idea?

Yes, those are very interesting ideas.  Doing that will require building the regexps on each update rather than once, when the defcustoms are changed, but that makes sense, because it will allow per-repository configuration.  We probably need to support prefixes and suffixes for the keywords.

We should probably discuss this idea in another issue now.  :)

Thanks for all your feedback!
