### ISSUE TITLE
ERROR: magit-todos: Not overriding bind of "jT" in ‘magit-status-mode-map’

### ISSUE THREAD

**Issue by olav35** [alphapapa/magit-todos#111]
I get error `magit-todos: Not overriding bind of "jT" in ‘magit-status-mode-map’.` on `M-x magit-todos-mode`. I looked through [these](https://github.com/alphapapa/magit-todos/issues?q=magit-todos%3A+Not+overriding+bind+of+%22jT%22+in+‘magit-status-mode-map’) issues, but I did not find a solution to my problem. 

**Steps to reproduce**
1. `$ emacs -Q`
2. Evaluate the following
```
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives
	     '("melpa" . "https://melpa.org/packages/"))
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(use-package magit)
(use-package magit-todos
  :after magit)
```
3. `M-x magit-todos-mode`

**Comment by alphapapa** [comment]
It's not an error: https://github.com/alphapapa/magit-todos/blob/78d24cf419138b543460f40509c8c1a168b52ca0/magit-todos.el#L379

**Comment by alphapapa** [comment]
See #95.
