### ISSUE TITLE
Avoid loading Org on init

### ISSUE THREAD

**Issue by meedstrom** [alphapapa/magit-todos#120]
I don't know if you consider this relevant or if I should make an issue with Doom Emacs instead.  Perhaps our `use-package` declarations should defer magit-todos until first time they call up a magit buffer anyway.

But if it's possible within this codebase to not load Org immediately, maybe it's a good feature? Takes work off the shoulders of Doom and other community configs.

**Comment by alphapapa** [comment]
So you mean that `magit-todos`'s loading Org was causing your Emacs startup time to be too long?  How much of a difference was it making?

**Comment by meedstrom** [comment]
With Org: 1.8s by stopwatch (Doom dashboard reports 1.5s, `emacs-init-time` reports 1.3s)

Without Org: 1.2s by stopwatch (Doom dashboard reports 0.9s, `emacs-init-time` reports 0.75s)

**Comment by jsigman** [comment]
Second that the requirement to load org early is stopping me from using this (otherwise) excellent package. The reason why has to do with the emacs-jupyter package, not startup time

**Comment by alphapapa** [comment]
Ok, if it's presenting a problem, I don't mind making that change.  Most cases won't involve an Org file anyway, and in the few that do, the change shouldn't be a performance problem, I think.

**Comment by alphapapa** [comment]
That should do it.  Please let me know if the problem is solved for you.
