### ISSUE TITLE
show TODO entrys in dot-directorys

### ISSUE THREAD

**Issue by hexaeder** [alphapapa/magit-todos#121]
Hello, first of all, thanks for the nice plugin :)
Using `magit-todos` I noticed that I don't see TODOs in hidden files/files in hidden directories. In my examples in a CI script `.github/CI.yml`. Even though the `magit-todos-exclude-globs` is `nil`. Am I missing some costumization here?

**Comment by alphapapa** [comment]
Thanks for the kind words.

Which files are used depends on the search backend used, how it's configured, as well as the globs setting.  e.g. using tools like `git grep` and `rgrep` automatically exclude files according to `.gitignore`, etc.

**Comment by hexaeder** [comment]
I am pretty sure I am using TODO items in the right format: If I start a new project in an empty folder
```
$> git init
$> mkdir foo .bar
$> echo "TODO: example1" >> .bar/testfile
$> echo "TODO: example2" >> foo/testfile
```
only the `foo/testfile` entry will be shown in magit. As soon as I `mv .bar bar` both are visible.

So I guess the config problem lies in my backend then... is it easy to determine which exact command (`rg` in my case) is run by `magit-todos`?

**Comment by hexaeder** [comment]
Okay `(add-to-list 'magit-todos-rg-extra-args "--hidden")` does the trick :) Thanks!

**Comment by alphapapa** [comment]
FYI, you should not use `add-to-list`, `setq`, etc. for customization options.  Use the customization system, which ensures that any setter functions associated with an option are run.
