### ISSUE TITLE
Inconsistent parsing of non-org keywords between hl-todos and magit-todos

### ISSUE THREAD

**Issue by elfsternberg** [alphapapa/magit-todos#124]
I write technical documentation, and I mostly write in Markdown. While writing documentation, I frequently have to leave a placeholder for a future pass, which often reads like this: `[TK: Where is this event handler defined?]`.  (["TK" is writerspeak for "to come"](https://en.wikipedia.org/wiki/To_come_(publishing)) since the only words that have 'tk' in them are pocketknife and hotkey, and case sensitivity matters.)

If I use hl-todo in a buffer with TK notes, it works.  It does not work with magit-todo.  If I put a space in front of the letters, so it looks like `[ TK: ...]`, then it works with magit-todos, but that's nonstandard and unaesthetic.

Expected behavior is that hl-todos and magit-todos find the _same_ todo entries.

**Comment by alphapapa** [comment]
As noted on #125, I don't think I necessarily intended that magit-todos behave exactly the same as hl-todo in this regard; the use of hl-todo in this package is mostly for convenience regarding display faces.  Anyway, see discussion there.
