### ISSUE TITLE
TODO paths aren't relative to the project root

### ISSUE THREAD

**Issue by chrisetheridge** [alphapapa/magit-todos#129]
![Screenshot 2022-04-25 at 17 03 16](https://user-images.githubusercontent.com/11030306/165116984-c945ab00-5155-4abb-af95-46c9ced1f651.png)

My TODO paths show up like this, which means I'm not able to do the nice path component grouping available via magit-todo. Is there any part of the README that I'm possibly missing?

Additionally, are there any examples of how to add a custom function for grouping items?

**Comment by alphapapa** [comment]
Which scanner backend are you using?

See https://github.com/alphapapa/magit-todos/blob/67fd80c2f10aec4d5b2a24b5d3d53c08cc1f05dc/magit-todos.el#L279  Just define a function that returns a string key for each item, and add the function to that option.

**Comment by chrisetheridge** [comment]
I am using `rg`. I'll take a look at the `magit-todos-group-by`, thank you!

**Comment by alphapapa** [comment]
Should be fixed by https://github.com/alphapapa/magit-todos/commit/7e6d6058ad466b7584f93f45b4b42cb7791ac83c.
