### ISSUE TITLE
Feature request: visit the containing file in another window

### ISSUE THREAD

**Issue by zhaojiangbin** [alphapapa/magit-todos#13]
Not sure if this is a matter of configuring magit-status. But would it be possible to have an option that, when enabled, pressing <kbd>return</kbd>, or another key, on a TODO item opens the containing file in another window?

In the magit-status buffer, if I press <kbd>return</kbd> on a recent commit, for example, the details info of that commit is shown in another window.

I see you have `magit-todo-section-map` defined but unused. I assume it means that you already have something similar in consideration?

**Comment by alphapapa** [comment]
I hadn't thought of that.  Maybe we need to use `magit-display-buffer-function`...

**Comment by alphapapa** [comment]
Hm, I'm not sure:
```
magit-display-file-buffer-function is a variable defined in ‘magit-diff.el’.
Its value is ‘magit-display-file-buffer-traditional’

  This variable may be risky if used as a file-local variable.

Documentation:
The function used by ‘magit-diff-visit-file’ to display blob buffers.

Other commands such as ‘magit-find-file’ do not use this
function.  Instead they use high-level functions to select the
window to be used to display the buffer.  This variable and the
related functions are an experimental feature and should be
treated as such.
```
And `magit-find-file` simply calls `switch-to-buffer`.

We could use `magit-display-buffer` instead of `switch-to-buffer`, but I'm not sure that would be consistent with the rest of Magit.

From looking at the code, it looks like it would be very complicated to make these to-do items work with `magit-diff-visit-file`, so I think that's not an option.  So we could try using `magit-display-file-buffer-function`, but it says that's an experimental feature (though I wonder if that's still the case).

What do you think?

> I see you have magit-todo-section-map defined but unused.

I don't know what you mean.  It is used.

**Comment by zhaojiangbin** [comment]
>>    I see you have magit-todo-section-map defined but unused.

> I don't know what you mean. It is used.

I see this in `magit-todos.el`:
```
(defvar magit-todo-section-map
  (let ((m (make-sparse-keymap)))
    (define-key m [remap magit-visit-thing] #'magit-todos--goto-item)
    m))
```
And nowhere else can I find any use of `magit-todo-section-map` in `magit-todos.el`. I am looking at commit 468317c90d868048bc449c2abfe93decd09c29bd.

By the way, what would this variable do? I tried pressing <kbd>m</kbd> in magit-status buffers. It always brings up the merge popup, instead of going to the item at point.

**Comment by alphapapa** [comment]
That map is used automatically by magit.  See `magit-insert-section`.

`m` is the variable used in that form for the map, not the key being bound.  The key is being remapped.

**Comment by zhaojiangbin** [comment]
Ah I was a fool. The `m` is a variable name. And it's passed to `define-key` as  a keymap.

I agree with you on `magit-diff-visit-file`. It'd be ideal if magit has something that works for all kinds of "visitable" items in magit-status buffers. 

I did a quick implementation by adding an boolean option to control what to call between `switch-to-buffer` and `switch-to-buffer-other-window`. It's very simple and seems to be working fine. I am going to create a pull request for you to review.

**Comment by akirak** [comment]
I thought of the same feature. I also think there should be another command which displays the location but keeps focus in the status window, which should be bound at `SPC`:

```emacs-lisp
   (define-key m [remap magit-diff-show-or-scroll-up] #'magit-todos--show-item)
```

I tried to implement this feature using `display-buffer`, but somehow it didn't work.

**Comment by akirak** [comment]
> AFAIK, by default, Magit displays diffs in another window, but when you press RET on a filename, it shows the file in the current window.

I wasn't aware of this behavior. I have looked into the source code,  and it turns out that `magit-diff-visit-file` command, which is run on file names and hunks, contains the following code for window management:

```emacs-lisp
      (cond ((called-interactively-p 'any)
             (magit-display-file-buffer buf))
            ((or other-window (get-buffer-window buf))
             (switch-to-buffer-other-window buf))
            (t
             (pop-to-buffer buf)))
```

That is, when it is called interactively, it uses `magit-display-file-buffer`, which is configured through `magit-display-file-buffer-function`, which seems to be `'magit-display-file-buffer-traditional` by default, which is defined as follows:

```
(defun magit-display-file-buffer-traditional (buffer)
  "Display BUFFER in the current window.
With a prefix argument display it in another window.
Option `magit-display-file-buffer-function' controls
whether `magit-diff-visit-file' uses this function."
  (if (or current-prefix-arg (get-buffer-window buffer))
      (pop-to-buffer buffer)
    (switch-to-buffer buffer)))
```

`magit-display-file-buffer` accepts a prefix argument to let it open the buffer in another window, and it is implemented here.

**Comment by akirak** [comment]
On the other hand, `magit-show-commit` invokes `magit-mode-setup`, which uses `magit-display-buffer` internally, which is configured through `magit-display-buffer-function` custom variable. This custom variable is introduced in magit 2.3.0, and its default value is `'magit-display-buffer-traditional`, which is defined as follows:

```emacs-lisp
(defun magit-display-buffer-traditional (buffer)
  "Display BUFFER the way this has traditionally been done."
  (display-buffer
   buffer (if (and (derived-mode-p 'magit-mode)
                   (not (memq (with-current-buffer buffer major-mode)
                              '(magit-process-mode
                                magit-revision-mode
                                magit-diff-mode
                                magit-stash-mode
                                magit-status-mode))))
              '(display-buffer-same-window)
            nil)))
```

I am confused. Please let me think about this for a while.

**Comment by akirak** [comment]
As you point out, maybe you should use `magit-display-file-buffer` for this purpose, but I am not sure. I think `magit-display-file-buffer-function` should be customizable, but it is just a `defvar` variable for now.

**Comment by alphapapa** [comment]
> I am confused. Please let me think about this for a while.

That is exactly how I feel.  :)

> Actually, the experimental status was added in 2015, so I think it is already stable.

Yeah I checked that too.  I thought about asking Jonas, but I figure he's busy enough with more important things, haha.

Well, I pushed a commit just now that adds a peek command.  Please let me know what you think.  If more changes or customization are needed, we can make them on top of that.  Thanks.

**Comment by akirak** [comment]
> 
I learned (or did I?) something very confusing about Emacs: it is
apparently not possible to move point in a buffer from within
with-current-buffer when that buffer is already displayed in another
window.  You must switch to that buffer.  Or something like that,
anyway.  The way that seemed most natural to do this, having a
function that would return a buffer with its point on the item, didn't
work when the buffer was already visible in another window: the point
simply didn't move.  Maybe there's a better way, but at least this
works.

This is a helpful insight. Thanks.

**Comment by alphapapa** [comment]
> This is a helpful insight. Thanks.

I hope so, but I'm still not sure I fully understand what was going on there...

**Comment by alphapapa** [comment]
I'm going to go ahead and close this, but if any further changes are desired, feel free to reopen.  Thanks.
