### ISSUE TITLE
Suggestion: Make magit-todos-jump-to-item (e.g. with universal-argument) open file in default editor

### ISSUE THREAD

**Issue by DivineDominion** [alphapapa/magit-todos#134]
I know, I know -- emacs should be the default editor :)

In my work, I have to use Xcode for programming. I'm relying on Emacs, Magit, and magit-todos for everything else, though. Following the TODOs opens the project files in Emacs, with LSP and all, but that's not useful, sadly.

I fiddled with a workaround to make `C-u RET` open the file associated with the `magit-todos` item in the default external editor. See code below

Please note this is WIP:

- I'm not sure if I'm designing the `cl-defun` correctly :)
- Also, the combination of `:peek t :externally t`doesn't make sense, so the parameter list isn't good. (Should this be symbol based like `:mode 'peek` and `:mode 'external`?)
- Maybe there's a better way than using `consult-file-externally` (which uses another package) to visit the file in the system default editor?
- Using `magit-todos-item-line` to jump to the line would be sweet, but that requires a much more complex setup. There's no universal way to open a file and go to a certain line. So each editor would have to be configured independently. That doesn't scale. And maybe that's a good reason not to include a feature like this.

What do you think?

Note: This includes a workaround for #133 by using `string-trim-right`.

```elisp
(require 'magit-todos)
(require 'consult)

(defun ct/magit-todos-open-item-default-editor (item)
  (let* ((filename (string-trim-right (magit-todos-item-filename item)))
         (path (expand-file-name filename)))
    (message (concat "Opening externally: \"" filename "\""))
    (consult-file-externally path)))

(cl-defun ct/magit-todos-jump-to-item (arg &key peek externally (item (oref (magit-current-section) value)))
  (interactive "P")
  (if (or externally arg)
      (ct/magit-todos-open-item-default-editor item)
    (magit-todos-jump-to-item :peek peek :item item)))

(define-key magit-todos-item-section-map [remap magit-visit-thing] #'ct/magit-todos-jump-to-item)
```

## `consult-file-externally` for reference

```elisp
(defun consult-file-externally (file)
  "Open FILE externally using the default application of the system."
  (interactive "fOpen externally: ")
  (if (and (eq system-type 'windows-nt)
           (fboundp 'w32-shell-execute))
      (w32-shell-execute "open" file)
    (call-process (pcase system-type
                    ('darwin "open")
                    ('cygwin "cygstart")
                    (_ "xdg-open"))
                  nil 0 nil
                  (expand-file-name file))))

```

**Comment by arademaker** [comment]
> I know, I know -- emacs should be the default editor :)

Well, sometimes the Emacs ecosystem does not help us! See https://github.com/emacs-lsp/lsp-haskell/issues/154, I am starting to consider selling my soul to VS Code...

**Comment by alphapapa** [comment]
In principle, I'm ok with making `C-u RET` use a different editor to open the file, but it should use built-in Emacs functionality, not anything from another package like `consult`.  Maybe you could just call `xdg-open` as `browse-url-xdg-open` does.

**Comment by DivineDominion** [comment]
@alphapapa My actual suggestion would be to inline (aka copy) the `consult-file-externally` function. xdg-open will only work on Linuxes, so to work properly, an OS switch is needed anyway. Would that be fine with you, or do you know any other built-in "open externally" function you'd prefer?

**Comment by alphapapa** [comment]
I'd prefer not to add OS-specific code to this project.  The best solution would be to propose that such a function (to open a file with the OS's default application) be added to Emacs itself, and then all packages could benefit from it.

Would you be willing to propose that something like `consult-file-externally` be upstreamed into Emacs?

**Comment by DivineDominion** [comment]
That sounds sensible and I don't know why that's not the case, tbh 🤔 I'll ask around for people with a better network in the emacs-devel list

**Comment by alphapapa** [comment]
Since there seems to be nothing else to do here, I'm closing, but feel free to let me know if that's not the case.
