### ISSUE TITLE
Setting Magit todos insert at fails if such a section is missing

### ISSUE THREAD

**Issue by sluedecke** [alphapapa/magit-todos#139]
Emacs rings its bell and tells me (in *Messages*): `magit-section-forward: No next section` if I set `magit-todos-insert-at` to anything but `top` or `bottom` and the section is not filled (i.e. no untracked files in repository):

**Section set to TOP:**

![image](https://user-images.githubusercontent.com/7710530/192442518-695a5383-c7a1-4e67-b5d3-a4ec02d2552b.png)

**Section set to "After untracked files":**

![image](https://user-images.githubusercontent.com/7710530/192442682-0d12206f-0bac-4435-bb61-0d08f2269a40.png)

**Comment by alphapapa** [comment]
Hm, maybe something changed in magit-section, or maybe this bug was never noticed before.  We'll probably need to add a fallback in case the section doesn't exist.  Thanks for reporting.

**Comment by alphapapa** [comment]
@sluedecke Thanks for reporting this.  Please let me know if it's now fixed for you.
