### ISSUE TITLE
Package hl-todo uses defvar-keymap, which is new in Emacs 29

### ISSUE THREAD

**Issue by rmolinari** [alphapapa/magit-todos#142]
I use Emacs v28.2 (the railwaycat version installed via Mac homebrew). When I try `magit-todos` with
```
(use-package magit-todos)
```
I get this error:
```
Debugger entered--Lisp error: (void-function defvar-keymap)
  (defvar-keymap hl-todo-mode-map :doc "Keymap for `hl-todo-mode'.")
  require(hl-todo)
  load-with-code-conversion("/Users/rory/.emacs.d/straight/build/magit-todos/ma..." "/Users/rory/.emacs.d/straight/build/magit-todos/ma..." t t)
  require(magit-todos nil t)
  [...]
```

Apparently `defvar-keymap` is new in 29.0.

Perhaps the documentation could mention that 29.0 is a requirement.

**Comment by alphapapa** [comment]
Hello,

This should not be a problem, because `hl-todo` requires the `compat` library, which provides `defvar-keymap`.  It would seem that something went wrong when you installed this package and its dependencies.

**Comment by rmolinari** [comment]
You are right. My package manager (straight) had installed `compat` in the past but did not update it when I tried `magit-todos`. Updating it manually makes everything work.

Thanks!
