### ISSUE TITLE
`magit-todos-section-map` hides the "j" keybinding expected in the status buffer

### ISSUE THREAD

**Issue by ghost** [alphapapa/magit-todos#143]
Hello,

I found that when using the jump command anywhere in the magit-status buffer, the transient menu was displayed as expected with the "T" and "l" options properly added after https://github.com/alphapapa/magit-todos/commit/ed4f5c49d726919529ef621dde56330dea3653a6. 

![image](https://user-images.githubusercontent.com/43751507/226057979-20716836-988c-446d-875e-3843237ceee4.png)

However inside the todo section I don't get a transient menu when pressing "j" and only have "T" and "l" available as options : 

![image](https://user-images.githubusercontent.com/43751507/226058111-7e5aa9de-3de1-4e0e-a5c8-8d480a525f32.png)

The following patch seems to fix the issue : 

![image](https://user-images.githubusercontent.com/43751507/226058327-9b5a9f5d-4b6b-425f-a967-863ed95fd20a.png)

```patch
---
 magit-todos.el | 3 +--
 1 file changed, 1 insertion(+), 2 deletions(-)

diff --git a/magit-todos.el b/magit-todos.el
index 0823ac9..158ff16 100644
--- a/magit-todos.el
+++ b/magit-todos.el
@@ -119,8 +119,7 @@ magit-status buffer.")
 
 (defvar magit-todos-section-map
   (let ((map (make-sparse-keymap)))
-    (define-key map "jT" #'magit-todos-jump-to-todos)
-    (define-key map "jl" #'magit-todos-list)
+    (set-keymap-parent map magit-status-mode-map)
     (define-key map "b" #'magit-todos-branch-list-toggle)
     (define-key map "B" #'magit-todos-branch-list-set-commit)
     (define-key map [remap magit-visit-thing] #'magit-todos-list)

base-commit: 7724259a008144b8cfc6cacdae3e764f207a03e7
-- 
```

EDIT: I should have mentioned I'm running emacs 30 and magit-todos version 1.6 (from melpa).

**Comment by alphapapa** [comment]
Thanks, I noticed this but hadn't gotten around to investigating.
