### ISSUE TITLE
magit-todos-item-first-path-component always returns "."

### ISSUE THREAD

**Issue by wentasah** [alphapapa/magit-todos#149]
When I set `magit-todos-group-by` as follows:

```elisp
(setq magit-todos-group-by '(magit-todos-item-first-path-component))
```

Magit status buffer shows the following for one of my project:

```
TODOs (34)
  . (34)
```

From reading the documentation, I have the impression that the output should look like this:

```
TODOs (34)
  doc (6)
  include (7)
  src (21)
```

That is, `doc`, `include` and `src` are top-level directories in my repository.

I'm not sure why I see just `.`. I guess it might be caused by a combination of tools in my system and other emacs packages. If you can tell me where to look, I can provide more information. It seems that `rg` is used as a scanner on my system, but I'm not sure.

Possible fix for this issue is available in #148. With it, the output contains all subdirectories, as expected.

**Comment by alphapapa** [comment]
Thank you.

1.  What platform/OS are you running on, and what version of Emacs and of magit-todos are you using?
2. What is the value of the variable `magit-todos-scanner`?
3. Does this behavior happen on every git repo you use, or just some?
4. If you expand the `.` section, what do the sections below look like?

**Comment by wentasah** [comment]
> 1. What platform/OS are you running on, and what version of Emacs and of magit-todos are you using?

Linux (NixOS unstable), Emacs 29.1, magit-todos 1.6

> 2. What is the value of the variable `magit-todos-scanner`?

`magit-todos--scan-with-rg`

rg version is:

```console
$ rg --version
ripgrep 13.0.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```
 
> 3. Does this behavior happen on every git repo you use, or just some?

In all repos.
 
> 4. If you expand the `.` section, what do the sections below look like?

```
    ./LibCarla/source/carla/client/LightManager.h TODO: std::vector<Light> GetAllLightsInRoad(RoadId id, LightGroup type = LightGr
    ./LibCarla/source/carla/client/LightManager.h TODO: std::vector<Light> GetAllLightsInDistance(Vec3 origin, float distance, Lig
    ./LibCarla/source/carla/client/detail/Episode.cpp TODO: Update how the map change is detected
    ./LibCarla/source/carla/rss/RssRestrictor.cpp TODO: determine acceleration and limit throttle
    ./PythonAPI/carla/setup.py.rej TODO: look at RSS
    ./PythonAPI/carla/setup.py.rej TODO: RSS...
    ./Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorData.cpp TODO: Handle death timer
```

> 5. If you set `magit-todos-scanner` to other options (using `M-x customize-option RET magit-todos-scanner RET`), does it affect this behavior?

Yes. In the following way:
- `find|grep`: buggy behavior described above
- `git diff`: No TODOs shown
- `git grep`: Correct (expected) behavior
- `rg`: buggy behavior described above

**Comment by alphapapa** [comment]
Ok, the fix in https://github.com/alphapapa/magit-todos/commit/7e6d6058ad466b7584f93f45b4b42cb7791ac83c should solve the problem for the rg backend.

The find|grep backend still has the leading `./` output, but as this comment says: https://github.com/alphapapa/magit-todos/blob/cadf29d1cc410c71a0020c7f83999d9f61721b90/magit-todos.el#L1384-L1385  So I'm not going to bother fixing that now.  Patches welcome, if anyone actually uses that backend and cares.  :)
