### ISSUE TITLE
Error message is displayed when there are no TODO 

### ISSUE THREAD

**Issue by lerouxrgd** [alphapapa/magit-todos#150]
Hello,

Since last commit I see the following error message:

```
error in process sentinel: magit-todos--async-when-done: process "magit-todos--scan-with-rg" failed with exit code 1.  Output:""
```

It happens when there are actually no TODO in the current repo.

**Comment by alphapapa** [comment]
Thanks.  I'll fix this soon.

**Comment by alphapapa** [comment]
@lerouxrgd That should fix it.  Please let me know if it does for you.

**Comment by lerouxrgd** [comment]
It is good now, thank you for the quick response !
