### ISSUE TITLE
Keyword matching is not respecting Git ignore rules even with `rg` installed

### ISSUE THREAD

**Issue by david-alvarez-rosa** [alphapapa/magit-todos#160]
I see that ignored files by Git are not taken into account, even when having ripgrep `rg` tool installed.

**Comment by alphapapa** [comment]
Hello David,

Is the `rg` scanner being detected and used by `magit-todos`?

**Comment by david-alvarez-rosa** [comment]
Thank you @alphapapa for replying.

Could you please guide me on how to perform the check above?

**Comment by alphapapa** [comment]
Check the value of `magit-todos-scanner`.
