### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by port19x** [alphapapa/magit-todos#170]
After installation, `magit-todos-mode` does nothing.

`magit-todos-update` greets me with the following error:
`magit-todos--section-end: Wrong type argument: (or eieio-object cl-structure-object oclosure), nil`

[Tested Repo](https://github.com/port19x/haproxy-mode)

Emacs 29

**Comment by alphapapa** [comment]
This package is known to work correctly when installed correctly.  That error suggests an installation or configuration problem.  Please try to reproduce the problem on a clean Emacs configuration, e.g. using https://github.com/alphapapa/with-emacs.sh

**Comment by alphapapa** [comment]
I see that your repository does not use the expected keyword format.  See option `magit-todos-keyword-suffix`.

**Comment by georgek** [comment]
Any fix for this? I've simply followed the README installation instructions, haven't modified `magit-todos-keyword-suffix` and I get the same error when running `magit-todos-update`.

It only seems to work for org repositories.

**Comment by alphapapa** [comment]
And I have confirmed yet again that the package installs and works without error in a clean Emacs configuration using Emacs 29.1 and his haproxy-mode repo.
