### ISSUE TITLE
Warning regarding buffer-local-value being an 'obsolete generalized variable'

### ISSUE THREAD

**Issue by mayersj1** [alphapapa/magit-todos#181]
Here's the full error/warning:

.local/straight/build-29.1/magit-todos/magit-todos.el: Warning:
    ‘buffer-local-value’ is an obsolete generalized variable.

I'm using the latest Doom Emacs and Magit ea0f07e, Transient 0.7.2, Git 2.45.1 Emacs 29.1 on MacOS

**Comment by alphapapa** [comment]
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=65555
