### ISSUE TITLE
Cannot open load file: No such file or directory, magit-todos when commiting

### ISSUE THREAD

**Issue by tad-lispy** [alphapapa/magit-todos#185]
After latest upgrade to my Doom Emacs, when I try to commit using Magit, it fails with the following details:

```
hint: Waiting for your editor to close the file...
Waiting for Emacs...
*ERROR*: Cannot open load file: No such file or directory, magit-todos
```

Everything works as expected after disabling `magit-todos`. There aren't yet any TODOs in my project. Your package used to work until today and brought me a lot of joy. Thanks for that. 

<details><summary>output from `doom/info`</summary>
<pre>
generated  Aug 22, 2024 17:13:11
system     NixOS 24.11.20240818.8a33541 (Vicuna) Linux 6.6.46 x86_64 pgtk
emacs      29.4 EMACSDIR=~/.emacs.d/
           EMACS=/nix/store/2jlqghnqr1zykxph112y8pkj74mwcppd-emacs-pgtk-29.4/bin/emacs
doom       3.0.0-pre PROFILE=_@0 HEAD -> master, origin/master, origin/HEAD dbcd30820
           2024-08-21 14:53:23 -0400 ~/.config/doom/
shell      /run/current-system/sw/bin/zsh
features   CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON
           LIBSELINUX LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER
           PGTK PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS
           TREE_SITTER WEBP XIM XWIDGETS GTK3 ZLIB
traits     gui server-running envvar-file custom-file
custom     connection-local-profile-alist connection-local-criteria-alist
           magit-todos-insert-after literate-calc-usimplify-results custom-safe-themes
modules    :config use-package :completion company vertico :ui doom doom-dashboard
           doom-quit (emoji +unicode) hl-todo modeline ophints (popup +defaults)
           (vc-gutter +pretty) vi-tilde-fringe workspaces zen :editor (evil
           +everywhere) file-templates fold (format +onsave) snippets word-wrap :emacs
           dired electric ibuffer undo vc :term vterm :checkers syntax (spell
           +flyspell +everywhere) grammar :tools direnv (eval +overlay) lookup lsp
           magit :lang clojure data elm emacs-lisp erlang (graphql +lsp) (haskell
           +lsp) json (java +lsp) javascript markdown (nix +lsp) org python rest (rust
           +lsp) (scheme +guile) sh web yaml (&user roc +lsp) :app (&user denote)
           (&user ai) :config (default +bindings +smartparens)
packages   (nushell-mode :recipe (:host github :repo mrkkrp/nushell-mode))
           (literate-calc-mode) (coffee-mode :pin
           35a41c7d8233eac0b267d9593e67fb8b6235e134) (transient :pin
           c2bdf7e12c530eb85476d3aef317eb2941ab9440 :recipe (:host github :repo
           magit/transient)) (with-editor :pin
           bbc60f68ac190f02da8a100b6fb67cf1c27c53ab :recipe (:host github :repo
           magit/with-editor))
elpa       vterm
</pre>
</details> 

Please let me know if I need to provide any additional details.

**Comment by alphapapa** [comment]
Hello,

Thanks for the kind words.  I'm glad that it's useful to you.

As you can see, this library hasn't changed in months, and it's known to work correctly.  If a problem started after upgrading DOOM, it would seem to suggest that there's a problem with DOOM.  So I'd suggest filing a report with the DOOM developers.  I do not use DOOM, and I cannot offer support for it.
