### ISSUE TITLE
Grammar in README

### ISSUE THREAD

**Issue by GildedHonour** [alphapapa/magit-todos#191]
In README:

> Install these required packages:

Does there exist "those required packages" too? If not, it should've been "Install the required packages:"
Alternatively, "Install these packages that are  required:"

**Comment by alphapapa** [comment]
I'm speechless.  If this is the kind of complaint that is being filed against this package now, it must be truly complete.

**Comment by GildedHonour** [comment]
Then you must publicly admit that I've made you an awesome complement :)

**Comment by alphapapa** [comment]
I regret that I must observe a misspelled word in your last comment.

**Comment by GildedHonour** [comment]
Now you've passed the test....  not bad.

**Comment by alphapapa** [comment]
Thanks.
