### ISSUE TITLE
Requiring ":" in magit-todos-search-regexp should be optional

### ISSUE THREAD

**Issue by aheaume** [alphapapa/magit-todos#21]
Hi!
Thanks for this great package, really cool.

I did struggle for a few minutes to make it work for me, until I found that `magit-todos-search-regexp` requires a `:` after a keyword to work at all, which I think is a sensible default, but not ideal in my case. I think it should at least be a documented in the README :)

FWIW, this is a temporary fix for anyone interested:

```emacs-lisp
;; Don't require the :, I actually prefer false positives
;; FIXME this will break if magit-todos-keywords is reset since the :set will reevaluate
(let ((keywords (seq-difference (mapcar #'car hl-todo-keyword-faces) magit-todos-ignored-keywords)))
    (setq magit-todos-search-regexp (rxt-elisp-to-pcre (rx-to-string `(or
                                                                       ;; Org item
                                                                       (seq bol (group (1+ "*"))
                                                                            (1+ blank)
                                                                            (group (or ,@keywords))
                                                                            (1+ space)
                                                                            (group (1+ not-newline)))
                                                                       ;; Non-Org
                                                                       (seq (group (or bol (1+ blank)))
                                                                            (group (or ,@keywords))
                                                                            (optional (1+ blank)
                                                                                      (group (1+ not-newline)))))))))
```

If I were to open a PR to make this behavior optional, maybe making the `(rx-to-string ...)` part its own customizable variable, would you consider merging it?

Have a nice day!

**Comment by alphapapa** [comment]
Hi Alexandre,

Thanks for mentioning this.  I've been thinking about this but I wasn't sure if it mattered to anyone else.

I just pushed a commit which adds an option for this.  It seems to work properly for me.  Please let me know what you think.

**Comment by aheaume** [comment]
Wonderful, thanks! Setting `magit-todos-require-colon` to `nil` works for me.
