### ISSUE TITLE
RET and SPC not working on TODO items

### ISSUE THREAD

**Issue by zhaojiangbin** [alphapapa/magit-todos#23]
I am getting 'user-error: There is no thing at point that could be visited' when pressing <kbd>RET</kbd> on any item. Pressing <kbd>SPC</kbd> is also not working. It's prompting for selecting a commit to show.

Tested ceeec11, with the minimal configuration as below:

```
(use-package magit-todos
  ;; :ensure t
  :load-path "~/CodeWorks/emacs/magit-todos"
  :commands (magit-todos-mode)
  :hook (magit-mode . magit-todos-mode)
  :config
  (setq magit-todos-recursive t
        magit-todos-depth 100
        magit-todos-update t))
```

`magit-version` has this output for me: "Magit 2.13.0, Git 2.18.0, Emacs 26.1, darwin"

I bisected the issue-11 branch. Turns out the offending commit is ccded3b20f22e5ee4752b88dfb425eba05cb71b3 where the keymap variable is renamed from `magit-todos-section-map` to `magit-todos-item-section-map`. In issue-11 branch, reverting this commit fixes it.

Trying to revert this commit in master ran into a conflict. The variable name `magit-todos-section-map` is now used by another keymap for <kbd>jT</kbd>.

I tried remapping `magit-visit-thing` and `magit-diff-show-or-scroll-up` in the same keymap as <kbd>jT</kbd>. That did not work.

**Comment by alphapapa** [comment]
Thank you.  Sorry for the trouble.  I forgot to make a one-symbol change when I changed the name of the keymap variable.  I just pushed to master, and it should be fixed now.
