### ISSUE TITLE
magit-todos: Not overriding bind of "jT" in ‘magit-status-mode-map’

### ISSUE THREAD

**Issue by matthew-piziak** [alphapapa/magit-todos#28]
This message appears every time I open a magit buffer. Is there a way to suppress it?

**Comment by alphapapa** [comment]
I'll look at the code again when I get a chance, but that shouldn't be
happening. By any chance did you put magit-todos-mode in a magit- hook?

**Comment by alphapapa** [comment]
Yeah, you don't need to do that, just activate it once.

**Comment by matthew-piziak** [comment]
I removed the `:hook` line and that's fixed it. Thank you!
