### ISSUE TITLE
Feature Request: Optionally disable keybindings

### ISSUE THREAD

**Issue by jojojames** [alphapapa/magit-todos#31]
Hi! Nice package.

I'm trying it out and it seems to bind jT unconditionally. I think the prefix bindings are a little awkward to unbind cleanly (since there's no remove-key equivalent in emacs).

As a workaround I'm define-key-ing nil on those binds and then manually binding j/k to evil's j/k keys right now.

Thanks!

**Comment by alphapapa** [comment]
Hi,

Hm, I'm not sure about this.  `j` is defined by Magit itself as the jump-to-section key prefix in `magit-status-mode-map`.  If `jT` is already defined in that map, `magit-todos` does not override it.

Generally, IIUC, best-practice is not to use options to control key bindings, so I'd rather not add an option for this unless it's really necessary.  And in this case, I don't think it is.  I think if you bind your keys in `magit-status-mode-map` before loading `magit-todos-mode`, `magit-todos` will not override that binding.  See this example:
```el
(let ((map (make-sparse-keymap)))
  (define-key map "j" 'something)
  (lookup-key map "jT"))  ;; => 1
```
As you can see, `lookup-map` for `jT` returns non-nil even though `j` is not bound to a prefix key and `jT` is not actually bound in that map, so when `magit-todos` does the same kind of check, if you have `j` bound to your own command, we won't override it.

So I would recommend doing something like this:
```el
(use-package magit
  :general (:keymaps magit-status-mode-map
                     "j" #'evil-next-line))
```
Of course, I don't use EVIL, so you will need to make the appropriate changes, but `general` is specifically designed to work with EVIL states, so it should be ideal for this.

**Comment by jojojames** [comment]
Hmnn, I think it's a little messy to have to bind something at the magit layer to avoid the binding in magit-todos especially if you want to late-bind that 'something'.

I'll work something out though, thanks.

**Comment by jojojames** [comment]
It's probably fine. You're probably right anyhow.

@fbergroth is putting in some work to do a compatibility layer here: https://github.com/emacs-evil/evil-collection/pull/177 so hopefully we'll get something evil users can use without any hiccups!

**Comment by mpereira** [comment]
People landing here from Google, the following should disable `magit-todos`'s evil-conflicting keybindings:

```emacs-lisp
(general-define-key
 :keymaps '(magit-todos-section-map magit-todos-item-section-map)
 "jT" nil
 "jl" nil
 "j" nil)
```

This would ideally be fixed in [evil-collection](https://github.com/emacs-evil/evil-collection/blob/master/modes/magit-todos/evil-collection-magit-todos.el). I might open a PR later.

**Comment by alphapapa** [comment]
> People landing here from Google,

Are you referring to something specific, like a specific problem that users may search for info about?

**Comment by mpereira** [comment]
@alphapapa yes. I rephrased my comment to be more specific, sorry for the confusion.

**Comment by alphapapa** [comment]
No problem, thanks.  As you probably know, I don't use EVIL myself, so yes, I would appreciate it if you contributed your fixes to evil-collection so I can continue to direct EVIL users there.  :)
