### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by tarsius** [alphapapa/magit-todos#34]
I saw this in `notes.org` and would like to encourage you to deal with that first.

> Option for when to refresh it
> 
> There should be an option for how often to refresh the to-dos section:
> 
> - always
> - manually
> - a number of seconds (not automatically, but whenever the
>   status buffer is refreshed and this many seconds have
>   elapsed)
>
> memoize can be used to implement this, probably with a proxy
> function to handle always/manually.

While I really liked `magithub` I never really used it because I couldn't get the refreshing and caching under control. I would like to give `magit-todos` a try, but am not looking forward to untimely refreshes.

It seems it shouldn't be too hard to implement an option `automatically-refresh` option, which could be set to `nil` and a command `do-refresh-now`. You can get fancier later on, but I think it would be a good idea to not scare those potential users away who don't want random hangs when refreshing the status buffer.

(Also is there a command to show the list of todos in a separate buffer? The amount of boilerplate that magit would require you to write for this is minimal, basically `magit-todos-mode` and `magit-todos-refresh-buffer`.)

Another thing I am not so excited about is the number of libraries I would have to install just for this one package, but who am I to talk, I am soon going to force an additional four libraries onto magit users. Regarding `anaphora`; I really think you should use *some* symbol prefix.

**Comment by tarsius** [comment]
>> Regarding anaphora; I really think you should use some symbol prefix.

> anaphora is a really nice library

Actually I confused that with your `elexandria`. Actually regarding `anaphora`: doesn't `dash` cover most of what that package provides?

**Comment by tarsius** [comment]
> I'm willing to make the changes so you can enjoy using it. It would be the least I could do after all you've given us.

oO Not sure how I feel about that.

Anyway, it's okay for a package to have a few convenience dependencies, but you are overdoing with four. I would recommend getting rid of `a` and `anaphora` (since the other two are fairly widely used already anyway).

**Comment by alphapapa** [comment]
> Actually I confused that with your elexandria.

Oh, ok.  Yeah, if I do publish that to MELPA, it will use a prefix.

> Actually regarding anaphora: doesn't dash cover most of what that package provides?

Not really.  Dash has `-when-let` and `-if-let`, but IIRC that's the extent of the overlap.  And when I've asked about adding macros to Dash that sort of bridge the gap between the packages, Dash's maintainers have indicated that they generally aren't interested.  So I don't think Dash is a replacement for Anaphora, and I don't think it ever will be.

> I would recommend getting rid of a and anaphora (since the other two are fairly widely used already anyway).

Well, I'm not using `a` for much, so that's not a big deal, I can remove that.  I'm reluctant to remove `anaphora` because, while `--when-let` can replace `awhen`,  `aprog1` has no counterpart in Dash, and it fits very well in the places it's used.  But I certainly want the primary author and maintainer of Magit to be able to use this package, so I can replace it as well.

**Comment by alphapapa** [comment]
I pushed a branch which removes the dependencies on `a` and `anaphora`.  It seems to work correctly, but I'm going to hold off on merging it into `master` for a bit, because I don't want to break anything for users.

**Comment by alphapapa** [comment]
Kept having to rebase it.  One of these days I will learn to wait and push when I'm done, but I always want to get branches pushed so they aren't just on my system...

**Comment by alphapapa** [comment]
Ok, I merged the branch into `master`, so it no longer depends on `a` or `anaphora`.  If there are no problems reported, I'll tag it as 1.1 soon.
