### ISSUE TITLE
TODO items link to wrong file locations in this customized keyword setting

### ISSUE THREAD

**Issue by dfeich** [alphapapa/magit-todos#36]
In my Org files I fairly often use checkboxes in bullet lists to indicate tasks that still are pending. I wanted to have them displayed with your excellent package. I configured for a test using the following

    '(magit-todos-keywords (quote ("TODO:" "- [ ]")))
    '(magit-todos-require-colon nil)

The magit buffer nicely displays the TODOs and also the checkbox list lines, but while the discplayed TODO lines still correctly link to the source locations in the Org file, the lines displaying the checkbox search hits all point to wrong locations in the file.

Thanks for this very useful package.
Derek

**Comment by alphapapa** [comment]
Hi Derek,

I'm glad you're finding it useful.

Funnily enough, I can't even get it to show checkbox items.  I did this:
```el
(custom-set-variables '(magit-todos-keywords '("TODO:" "-  [ ]") t)
                      '(magit-todos-require-colon nil t))
```
But then I only see `TODO` items, not checkbox ones.  I was able to get `rg` to match the items by editing the final regexp in PCRE form and running it in a shell, but I can't get it to work in `magit-todos`, so I'm curious how you managed that, haha.  I'll need to get that working before I can figure out why the positions aren't correct.

In case it's relevant, what platform are you on, and which scanner are you using?

Thanks.

**Comment by dfeich** [comment]
Hi Alphapapa

Thanks a lot for the fix. I tested it and saw that it is good to make sure and reload the whole module (I seemed to have some interference effects, initially). Then it went like a charm. Very useful, indeed!

When I wanted to port the configuration from the customization file into my main init.el, I found that it is necessary to explicitely set `magit-todos-keywords-list` after changing the `magit-todos-keywords` value, mirroring what you do in the `:set` part of the `defcustom` statement of `magit-todos-keywords` (btw. I am learning quite a bit of new elisp reading your code - was not aware of these defcustom features).

So, this is what I am ending up in use-package:

```elisp
(use-package magit-todos
  :config (setq  magit-todos-keywords '("TODO:" "* TODO" "- [ ]")
		 magit-todos-require-colon nil
		 magit-todos-scanner 'magit-todos--scan-with-rg
		 magit-todos-keywords-list (seq-difference
					    magit-todos-keywords
					    magit-todos-ignored-keywords)))
```
Best regards and thanks again,
Derek

**Comment by alphapapa** [comment]
Hi Derek,

Thanks for testing it.

All of those problems should go away if you use the `customize` interface instead of trying to set things manually.  ;)  I don't know if you were using this, but the `use-package :custom` keyword doesn't seem to work with custom setters; there's another issue here about it, and I filed a bug about it with `use-package`.  Besides that, you should be able to use `customize-set-variable` on `magit-todos-keywords`, like:
```el
(customize-set-variable 'magit-todos-keywords '("TODO") "Set manually outside of customize")
```
