### ISSUE TITLE
Submit to MELPA

### ISSUE THREAD

**Issue by yiufung** [alphapapa/magit-todos#4]

**Comment by yiufung** [comment]
Was wondering why it isn't on MELPA but then saw the discussion on Reddit. Look forward to it!

**Comment by alphapapa** [comment]
Thanks, I'll be submitting it soon.

**Comment by alphapapa** [comment]
https://github.com/melpa/melpa/pull/5564

**Comment by sejgit** [comment]
wow -- you posted 8 days ago -- does it really take more than eight days to show up in list-packages.  never realized this until this example.

**Comment by OkanEsen** [comment]
Are you for real, @sejgit? You realize, that this is an open source project an @alphapapa is doing this in his free time, right? He can work on this project whenever he wants and doesn't need to justify himself to anbody.

**Comment by sejgit** [comment]
@OkanEsen , you obviously misunderstood my post.  It was "what I learned today" about how long it takes from when a person, @alphapapa in this case, posts to Melba for it to show up in an emacs 
list-packages pull.  That was a comment on process, not on anyone (including the melpa curators) in the open source community.  Please don't assume someone's intentions before you read.

**Comment by OkanEsen** [comment]
Oh well, that went right over my head, I'm deeply sorry @sejgit for accusing you of something you never did.

I should read a comment one more time before running into any conclusions, sorry again!

**Comment by OkanEsen** [comment]
Seems like the PR got merged: https://github.com/melpa/melpa/commit/b4544ab55d2c8b8c3b7eb739b9fb90ebb246d68b.

**Comment by yiufung** [comment]
Yep it is! Congrats!
