### ISSUE TITLE
Feature request: Add customization to ignore directories

### ISSUE THREAD

**Issue by magnusmalm** [alphapapa/magit-todos#41]
A customization to ignore directories would be nice to have. One can of course use Extra Arguments customization to ignore directories (for instance "--glob=!{dir1,dir2}" for ripgrep) but a customization for directories on the form of a list with strings of directories would be a nice addition.

I have a WIP branch going [here](https://github.com/magnusmalm/magit-todos.git) which is not quite there yet.

I've not had that much of Elisp experience so I am not quite up to speed on all the ins and outs of the codebase yet so please, be gentle. :)

**Comment by alphapapa** [comment]
Hi,

Yes, I’m planning to add an ignore-globs option, which I hope to make work with all the scanners. See the notes.org file for some of the plans and ideas.  PRs are always welcome, of course. 

Thanks.

**Comment by magnusmalm** [comment]
I've managed to get directory ignoring to work Good Enough (tm) for me.

The following problems exists:
1. I get the following error when **magit-todos-update** is t:
     **eieio-oref: Wrong type argument: (or eieio-object class), nil, obj**
See [magit-todos-debug.txt](https://github.com/alphapapa/magit-todos/files/2251086/magit-todos-debug.txt) for a bit more info on this.
Using edebug and stepping, I think things go bad when
**(magit-todos--insert-items (current-buffer) magit-todos-item-cache)**
is called in **magit-todos--insert-todos**.
But right now I cannot seem to get edebug to instrument the function again. I'll try to figure out what I am doing wrong.

2. The ripgrep scanner is the only one that works. The git grep scanner appears to be a bit more involved to get to work with multiple directories.

Point 1 feels a little over my head right now as I suspect there is some aspects of the async process and how the magit sections are created/updated. I need to get a little more experience with debugging elisp in general and then async processes after that.

Point 2 needs a bit more digging into git I guess.

Anyway, just a quick update on the progress.

**Comment by magnusmalm** [comment]
Sorry, forgot to add links to the commits I've made. There's just two of them and quite small actually:

Regarding point 1:
https://github.com/magnusmalm/magit-todos/commit/fc8354988e88468940ee89a3efd2bd9eb7da6147

Regarding point 2:
https://github.com/magnusmalm/magit-todos/commit/2b81cca9cf0234de6ab30e62205328963a2466ae

It seems so simple and like it should work as intended.

I am gonna try to run emacs -Q + magit + magit-todos just to rule out that any other magit related package interfers (should have thought about that eariler...).

As you say, theoretically, it should work. :)

Thanks for the input so far.

**Comment by alphapapa** [comment]
Here's what I was thinking: https://github.com/alphapapa/magit-todos/tree/feature/ignore-globs  It seems to work for me.  Please let me know what you think.

**Comment by magnusmalm** [comment]
Very nice. Works like a charm for me too.

I cannot quite see what made my changes not working, but I'll try to ignore those and be happy that I've learned to use edebug a bit more. :)

Much appreciated.

**Comment by alphapapa** [comment]
Forgot to close this.
