### ISSUE TITLE
Feature Request: Allow to scan .org files out of vc

### ISSUE THREAD

**Issue by muihlinn** [alphapapa/magit-todos#44]
More often than not I use .org files to keep the track of code issues, misc notes, drafts, or mid/long-term client requests progress which I don't want to be under source control.

Until now I manage all those files under an agenda category (also I track the time there, so this use won't go), but It'll be nice to have the choice of adding the relevant ones (manually choosen) to magit-todos results while still being able to ignore them in the repo.

**Comment by alphapapa** [comment]
Do you mean that you store them in the repo working tree but don't add them to git, or that you store them outside the repo?  If the former, that should already work.  If the latter, I guess that could be done by passing extra paths to the scanners.

**Comment by muihlinn** [comment]
I store it in a subdirectory under the repo root, then add it to .gitignore to avoid having them in the way in untracked files.

**Comment by muihlinn** [comment]
Just learned that rg .ignore file allows for negative patterns and takes higher priority than . gitignore, which solves my problem. Still might be a consideration for other scanners like git-grepEl 21 jul. 2018 0:51, alphapapa <notifications@github.com> escribió:Do you mean that you store them in the repo working tree but don't add them to git, or that you store them outside the repo?  If the former, that should already work.  If the latter, I guess that could be done by passing extra paths to the scanners.

**Comment by alphapapa** [comment]
I want to avoid unnecessary complexity and configuration, so I'm closing this for now.  If other users express a need for additional configuration that isn't covered by the available options, we can consider it.  Thanks.

**Comment by waymondo** [comment]
This is also my desired workflow. I have a gitignored `TODO.org` file in the root of my repos, and would like to keep it out of VC while still showing the todos in the magit status buffer. Creating an `.ignore` file with the following works for `rg`:
```
!TODO.org
```

It's not a horrible solution, but the solution would vary per grepping engine.

**Comment by muihlinn** [comment]
I'm fine as is, thanks much
