### ISSUE TITLE
No items with "find|grep" scanner

### ISSUE THREAD

**Issue by Ambrevar** [alphapapa/magit-todos#46]
With `(setq magit-todos-scanner #'magit-todos--scan-with-find|grep)`, I get a `*magit-todos--scan-with-find|grep*` buffer with lines like
```
./init-eshell.el:3481:;;; TODO: ls: Sort using locale.
```

So I guess that part works.

Nothing items get printed in the magit status buffer however.

Any clue?

**Comment by Ambrevar** [comment]
I first tried with `customize-group RET magit-todos RET` with the same result.

**Comment by alphapapa** [comment]
Thanks, I found the problem and how to fix it.  I'm not sure why it wasn't working, that way, but it should be fixed.  Will merge soon...

**Comment by Ambrevar** [comment]
Thanks!
