### ISSUE TITLE
Issue with magit-todos--keyword-face

### ISSUE THREAD

**Issue by benjaminor** [alphapapa/magit-todos#51]
Hi, since last week, I get this following error when opening the magit status buffer while magit-todos-mode is active:

`Debugger entered--Lisp error: (wrong-type-argument characterp (:inherit hl-todo :foreground "#cc9393"))
  string((:inherit hl-todo :foreground "#cc9393"))
  magit-todos--keyword-face("TODO")
  magit-todos--format-plain(#s(magit-todos-item :filename "elisp/base-extensions.el" :org-level nil :line 229 :column nil :position nil :keyword "TODO" :description "complete bindings"))
  magit-todos--insert-group(:type todos :heading "TODOs (2)" :group-fns nil :items (#s(magit-todos-item :filename "elisp/base-extensions.el" :org-level nil :line 229 :column nil :position nil :keyword "TODO" :description "complete bindings") #s(magit-todos-item :filename "elisp/base.el" :org-level nil :line 56 :column nil :position nil :keyword "TODO" :description "write package to support auto-update, like for package.el")) :depth 0)
  magit-todos--insert-items(#<buffer magit: .emacs.d> (#s(magit-todos-item :filename "elisp/base-extensions.el" :org-level nil :line 229 :column nil :position nil :keyword "TODO" :description "complete bindings") #s(magit-todos-item :filename "elisp/base.el" :org-level nil :line 56 :column nil :position nil :keyword "TODO" :description "write package to support auto-update, like for package.el")))
  magit-todos--scan-callback(#<buffer magit: .emacs.d> "\\(?:^\\(?8:[^:]+\\):\\(?2:[[:digit:]]+\\):\\(?1:\\*+\\)?.*?\\(?4:\\(?:\\?\\?\\?\\|DONT\\|F\\(?:AIL\\|IXME\\)\\|H\\(?:ACK\\|OLD\\)\\|KLUDGE\\|NEXT\\|OKAY\\|PROG\\|T\\(?:EMP\\|HEM\\|ODO\\)\\|XXXX?\\)\\):?\\(?:[[:blank:]]+\\(?5:.+\\)\\)?\\)" #<process magit-todos--scan-with-git-grep>)
  apply(magit-todos--scan-callback (#<buffer magit: .emacs.d> "\\(?:^\\(?8:[^:]+\\):\\(?2:[[:digit:]]+\\):\\(?1:\\*+\\)?.*?\\(?4:\\(?:\\?\\?\\?\\|DONT\\|F\\(?:AIL\\|IXME\\)\\|H\\(?:ACK\\|OLD\\)\\|KLUDGE\\|NEXT\\|OKAY\\|PROG\\|T\\(?:EMP\\|HEM\\|ODO\\)\\|XXXX?\\)\\):?\\(?:[[:blank:]]+\\(?5:.+\\)\\)?\\)" #<process magit-todos--scan-with-git-grep>))
  #f(compiled-function (&rest args2) #<bytecode 0x2ef53e5>)(#<process magit-todos--scan-with-git-grep>)
  async-when-done(#<process magit-todos--scan-with-git-grep> "finished\n")`

Do you know what could be the cause of this error?

**Comment by alphapapa** [comment]
Hi,

No, that is very strange.

1.  I just pushed a fix for what should be an unrelated issue, but it touches this code.  Please test on the new `master` (or wait for the package to be rebuilt by MELPA).

2.  If that doesn't fix it, please paste the value of `hl-todo-keyword-faces`.

Thanks.

**Comment by benjaminor** [comment]
Alright, I updated magit-todos and the issue is gone now.
Thanks for your help.
