### ISSUE TITLE
magit-todos-update hangs on MacOS

### ISSUE THREAD

**Issue by smaret** [alphapapa/magit-todos#54]
`magit-todos` looks like a very nice emacs package, but I can't get it to work on my computer (Mac OS 10.13.2, Emacs 26.1, magit-todos 20180904.1753 installed from MELPA). 

I've turn on the `magit-todos-mode` in the `magit` buffer for my project. Typing `j-T` displays: "No TODOs section". Then when I try to update the list manually with `magit-todos-update` Emacs hangs.

I've installed both `ripgrep` and `git grep` and the method is set to "Automatic".

**Comment by alphapapa** [comment]
Hi Sebastien,

> Typing j-T displays: "No TODOs section"

I guess that means that you opened the magit-status buffer and then enabled magit-todos-mode.  It's intended that you enable magit-todos-mode (which is global, not buffer-local) and then open the magit-status buffer.  But in case you do it that way, if you refresh the magit-status buffer by pressing `g`, it should work then.

**Comment by alphapapa** [comment]
I made a couple of fixes to avoid the loop and tell the user that the mode should be activated first.  Thank you for reporting this issue.
