### ISSUE TITLE
Support usernames in tokens

### ISSUE THREAD

**Issue by thiderman** [alphapapa/magit-todos#56]
I've been enjoying the custom to sign your TODO items with your username, e.g.;

```
TODO(thiderman): Fix the foobar and the bizbaz
```

Setting the `magit-todos-require-colon` setting to `nil` makes the code find tokens, but it seems that it cannot read the contents and just prints the tokens;
![20181021 195738](https://user-images.githubusercontent.com/155394/47270405-97cfe000-d56b-11e8-87d1-c391fc1cd758.png)

That last one is the only one that doesn't have a username (I have a `yas` snippet that expands with my username, so I rarely forget it).

I understand that this is an edge case and not how most projects does it. However, if it is not too much of a bother to add support of these kinds of tokens, I'd be the happiest camper! This is a lovely project, but it simply doesn't work for almost anything I work on, both professionally and during my spare time.

Cheers! :tada:

**Comment by alphapapa** [comment]
I think we can do this by changing the require-colon setting to a keyword-suffix setting, which could be nil to match items like those. I'll add this when I get a chance. Thanks for suggesting.

**Comment by alphapapa** [comment]
@thiderman I think that should do it, and the default should work for you.  Please let me know if it does!

**Comment by thiderman** [comment]
Absolutely!

![20181124 193524](https://user-images.githubusercontent.com/155394/48971900-7bb6d700-f020-11e8-961e-61a0cc6997a4.png)

Is that good? :dancer:
