### ISSUE TITLE
TRAMP support

### ISSUE THREAD

**Issue by Ambrevar** [alphapapa/magit-todos#57]
When running `magit-status` over TRAMP (ssh connection), I notice that there is a complex `grep` command (I use that) hanging in the background eating a whole CPU.

I haven't started investigating yet, just letting you know in case you are aware of this and if you have suggestions how to handle this gracefully.

Is it possible to disable magit-todos over TRAMP?

**Comment by alphapapa** [comment]
Actually I have no idea how TRAMP behaves with respect to this package. Is the grep command running on the local machine or the remote one?

**Comment by Ambrevar** [comment]
I'm not sure either.  Any idea how I can inspect the default-directory the command is run in?
I'm not familiar with async.el.

With regular emacs, there is `call-process` for local processes and `process-file` for processes over TRAMP.

**Comment by alphapapa** [comment]
How do you know there is a stuck grep process?

**Comment by bascht** [comment]
@alphapapa I think I ran into the same issue as @Ambrevar. It looks like emacs will start the process on my local machine (screenshot from htop):

![Screenshot-2019-07-11-165037](https://user-images.githubusercontent.com/51264/61061314-4965b880-a3fc-11e9-8441-d1b94a582a63.png)

If I check the process via `ps` it looks like it will just append `./` which will fire up `rg` for my complete home folder:

```
bascht   17888  7726 99 16:51 pts/8    00:00:07 rg --no-heading --line-number ^(\*+)[[:blank:]]+(DONT|F(?:AIL|IXME)|H(?:ACK|OLD)|KLUDGE|NEXT|OKAY|PROG|T(?:EMP|HEM|ODO)|(?:XXX|\\\?\\\?\\\?)\+)[[:space:]]+(.+)|(?:^|[[:blank:]]+)(DONT|F(?:AIL|IXME)|H(?:ACK|OLD)|KLUDGE|NEXT|OKAY|PROG|T(?:EMP|HEM|ODO)|(?:XXX|\\\?\\\?\\\?)\+)(?:\([^)]+\))?:(?:[[:blank:]]+(.+))? ./
```

Which would explain the emacs hang and the fans spinning up. :grimacing: 
Let me know if I can supply more information to help debugging this.

**Comment by alphapapa** [comment]
Sorry, I have no idea how to deal with TRAMP, and I'm reluctant to complicate the code by adding TRAMP-specific workarounds.  I also don't use git over TRAMP, so I don't need to use this package over TRAMP.  If someone is interested in contributing patches, I'll be glad to consider them.

**Comment by dieggsy** [comment]
@alphapapa is there any way to at least disable the package on remote repositories?

**Comment by alphapapa** [comment]
I don't know.  I don't know how TRAMP works internally.

**Comment by alphapapa** [comment]
@Ambrevar @bascht @dieggsy I added support for TRAMP and it seems to work for me.  Note that you may need to configure it for each repository if the remote machine's configuration differs from yours.  Please let me know how it works for you.

**Comment by Ambrevar** [comment]
Thanks a lot!
