### ISSUE TITLE
Section "TODOs" not found 

### ISSUE THREAD

**Issue by smurphy8** [alphapapa/magit-todos#59]
+ magit-todos        20181124.2022 installed         
+ magit              20181206.2321 installed
+ emacs version 26.1

The TODOs section doesn't seem to be created?  

I am not very familiar with elisp but would be glad to help find out why.  Perhaps though I am just doing something silly!

**Comment by alphapapa** [comment]
1.  There is no colon after the keyword.  See the `keyword-suffix` option.
2.  Did you activate `magit-todos-mode`?

**Comment by smurphy8** [comment]
:( a colon all because of a colon thanks!

**Comment by alphapapa** [comment]
No problem.  You can disable the colon requirement if you want.
