### ISSUE TITLE
Coloring is inconsistent with magit

### ISSUE THREAD

**Issue by m-cat** [alphapapa/magit-todos#64]
In the `magit-status` buffer, the number in parentheses after "TODOs" has a font face applied to it, which is not the case in the rest of `magit-status`.

Pictorial evidence:

https://www.dropbox.com/s/ehpub0y0d9d4f7o/Screen%20Shot%202019-01-10%20at%2011.27.15%20PM.png?dl=0

Here we see that `(5)` is fontified, whereas `(1)` after "Unstaged changes" is not.

I find this incredibly distracting.

I'm willing to fix this myself to get some more experience with EPD.

**Comment by alphapapa** [comment]
I'm aware, however it doesn't distract me or anyone else so far, so I haven't spent the time to change it.  Patches welcome if you feel like it.

**Comment by alphapapa** [comment]
Assigned to you.  :)
