### ISSUE TITLE
Option to show hidden files

### ISSUE THREAD

**Issue by blaenk** [alphapapa/magit-todos#7]
I was wondering why it wasn't working in my dotfiles directory and it's because most files are hidden (because they're dotfiles). I typically fix this by making sure that hidden files are shown by passing the `--hidden` flag to ag. Perhaps there should be a way of splicing in additional parameters to ag, or an option created to specifically enable this, or have `--hidden` passed by default.

**Comment by alphapapa** [comment]
I think we can do that.

This never-ending configuration... :)
