### ISSUE TITLE
magit-todos-exclude-globs not working

### ISSUE THREAD

**Issue by gjm** [alphapapa/magit-todos#71]
Hi.

I want to ignore all files in `public/vendor` directory. I added the local variable to `.dir-locals.el`:
```
((magit-status-mode
  (magit-todos-exclude-globs . "public/vendor")))
```

When I open `magit-status` I get:

```
mapcar: Wrong type argument: sequencep, 112
```

Am I doing something wrong?

**Comment by alphapapa** [comment]
The error message hints at the problem: a sequence is expected, but it only found an integer (which, in Emacs, is what characters are).  The variable is supposed to be a list of strings, but you set it to an atom.

The solution is to change the value from an atom to a list of string(s).  So you should not use dot-notation there.

This is explained in [the readme](https://github.com/alphapapa/magit-todos#tips) in tip IV.

You could say this is a quirk of how Emacs's dir-local variables work.  You should consult the manual for more information on how to set them properly.

**Comment by gjm** [comment]
Thanks that fixed it! Didn't notice the parens in the docs.
