### ISSUE TITLE
Configurable magit-status section position

### ISSUE THREAD

**Issue by blaenk** [alphapapa/magit-todos#8]
I'm not sure how exactly the magit sections api works but if it works by letting one choose after what section to insert a section (I think the popup shortcut api works this way), then it might be nice if it's user configurable so the user can choose where to insert the todos, or short of that, if an option is added to add it to the very end.

**Comment by alphapapa** [comment]
Yes, that's a good idea.  Magit does indeed allow that, but in the `async-ag` branch, I have to sort of hack around it since it's not designed to be called after the status buffer is finished.  I think it might still be possible to customize that, however it might require users to know a little bit about how the magit sections work.  I'll see what I can do.  :)

**Comment by blaenk** [comment]
Sounds good! It's not a big deal I guess, but maybe at the very least an option specifically to have it appear at the end might be appreciated by some. Currently it's showing up before the "unpushed/unmerged commits" list which I think I look at more often than todos.

**Comment by alphapapa** [comment]
That's a good point.  I think I'll go ahead and move it to the bottom for now, and maybe it can be customized later.

BTW, if you have time, please test the `async-ng` branch and let me know how it works for you.  I think it's working well enough that I can merge it into `master`, but since it involves async processes and a bit of hackery around Magit, I want to be careful.

**Comment by blaenk** [comment]
Switched over to `async-ag` (got confused for a second because you wrote `async-ng` and wasn't sure why straight.el was complaining :).

Perhaps you might remember from #7 that in my dotfiles repo all of the TODOs are in hidden files (dotfiles after all), so previously it would return a non-zero exit code and show an error in the message buffer. On `async-ag` it seems to cause worse issues now though rather than just printing out that message it seems to corrupt the status buffer.

```
error in process sentinel: save-current-buffer: Buffer *ag-scan-async*<3> has no process
error in process sentinel: Buffer *ag-scan-async*<3> has no process
```

Backtrace:

```
Debugger entered--Lisp error: (error "Buffer *ag-scan-async*<4> has no process")
  delete-process(nil)
  (save-current-buffer (set-buffer (process-buffer magit-todos-active-scan)) (delete-process magit-todos-active-scan) (kill-buffer))
  (progn (save-current-buffer (set-buffer (process-buffer magit-todos-active-scan)) (delete-process magit-todos-active-scan) (kill-buffer)))
  (if (buffer-live-p (process-buffer magit-todos-active-scan)) (progn (save-current-buffer (set-buffer (process-buffer magit-todos-active-scan)) (delete-process magit-todos-active-scan) (kill-buffer))))
  (progn (if (buffer-live-p (process-buffer magit-todos-active-scan)) (progn (save-current-buffer (set-buffer (process-buffer magit-todos-active-scan)) (delete-process magit-todos-active-scan) (kill-buffer)))) (setq magit-todos-active-scan nil))
  (if magit-todos-active-scan (progn (if (buffer-live-p (process-buffer magit-todos-active-scan)) (progn (save-current-buffer (set-buffer (process-buffer magit-todos-active-scan)) (delete-process magit-todos-active-scan) (kill-buffer)))) (setq magit-todos-active-scan nil)))
  magit-todos--insert-items()
  run-hooks(magit-status-sections-hook)
  magit-run-section-hook(magit-status-sections-hook)
  magit-status-refresh-buffer()
  apply(magit-status-refresh-buffer nil)
  magit-refresh-buffer()
  magit-refresh()
  funcall-interactively(magit-refresh)
  call-interactively(magit-refresh nil nil)
  command-execute(magit-refresh)
```

I'm sorry but I don't have time to look into this further at the moment, but hopefully that's better than nothing for now.

On another repo where the TODOs aren't in hidden files (which also worked on master, i.e. it didn't cause ag to return non-zero), it seems to work fine.

I'll let you know if I run into anything else.

**Comment by blaenk** [comment]
My dotfiles repo is at https://github.com/blaenk/dots if you feel like reproducing on your own, but it'll probably happen whenever there are no TODOs found at all? Not sure.

**Comment by alphapapa** [comment]
> Switched over to async-ag (got confused for a second because you wrote async-ng and wasn't sure why straight.el was complaining :).

Oops, I can't seem to type today...

> Perhaps you might remember from #7 that in my dotfiles repo all of the TODOs are in hidden files (dotfiles after all), so previously on master, the ag process would return a non-zero exit code and show an error in the message buffer. 

I just pushed a fix for that (I hope, anyway).  Thanks.

> On async-ag it seems to cause worse issues now though rather than just printing out that message it seems to corrupt the status buffer.

I have seen the backtrace you reported, but I haven't seen corruption of the status buffer.  What do you mean exactly?  If it happens again, could you take a screenshot?

> On another repo where the TODOs aren't in hidden files (which also worked on master, i.e. it didn't cause ag to return non-zero), it seems to work fine.  ... it'll probably happen whenever there are no TODOs found at all? Not sure.

I think it works fine if there are no TODOs found, as I use it in repos that have none, and it doesn't do any harm.  However, with all the options, it's possible you're using a combination that causes a problem.  Can you try it with `rg`, `ag`, and the Emacs scanner method?

Thanks for your help.

**Comment by blaenk** [comment]
> I have seen the backtrace you reported, but I haven't seen corruption of the status buffer. What do you mean exactly? If it happens again, could you take a screenshot?

Will do. Basically after pressing `g` in the status buffer, the sections were all auto-expanded and the highlighting was off, but I realize now it's basically that all of the sections were expanded and the point moved to the beginning of the buffer. When I move them within a particular section it rehighlights that section.

![status buffer](https://i.imgur.com/9CGFlGq.png)

> I think it works fine if there are no TODOs found, as I use it in repos that have none, and it doesn't do any harm. However, with all the options, it's possible you're using a combination that causes a problem.

Not sure which options? I only have this:

``` elisp
(setq magit-todos-depth -1
      magit-todos-max-items 0)
```

**Comment by alphapapa** [comment]
> Will do. Basically after pressing g in the status buffer, the sections were all auto-expanded and the highlighting was off, but I realize now it's basically that all of the sections were expanded and the point moved to the beginning of the buffer. When I move them within a particular section it rehighlights that section.

That's strange, I haven't seen anything like that.  Please try updating the package and then restarting Emacs to ensure only the latest version is loaded.

> Not sure which options? I only have this:

Ok.  You're using the ag scanner, right?  Please try also with the rg one if you can.  It should work much better in general.

**Comment by Amorymeltzer** [comment]
This doesn't seem present?
