### ISSUE TITLE
Branch diff scanner slows down magit-refresh significantly

### ISSUE THREAD

**Issue by aaronjensen** [alphapapa/magit-todos#85]
Hi there,

magit-todos is great—thank you for it! I was noticing today that the new branch diff scanner is synchronous and nearly doubles the time it takes to refresh magit, which slows down things like staging files. While I can disable the scanner, I'm curious if it'd be possible to have it be async as well, like the regular scanner so that it doesn't give as much of a hit on the refresh?

Thanks!

**Comment by alphapapa** [comment]
That must be a large repo with a lot of to-dos.

The diff scanner requires doing more parsing inside of Emacs, because no external command (that I've been able to find) provides the necessary output.  It might be possible to do that with `async` in a separate Emacs process.

**Comment by aaronjensen** [comment]
Got it. It's a large repo, but only a about 4 or 5 todos. It's possible that it was a large branch that I was on. I've since discovered magit-todo's caching, so I think I'm good.
