### ISSUE TITLE
Writes TODOs to end of file at first start of magit-status

### ISSUE THREAD

**Issue by KaratasFurkan** [alphapapa/magit-todos#88]
Every time i open a project in emacs and magit-status for the first time, magit-todos writes TODOs at the end of the file.

I use spacemacs and did not configure anything about magit or magit-todos.

Here is a 7 seconds of screencast what the issue i encounter:
https://streamable.com/5ne33

**Comment by alphapapa** [comment]
I don't use Spacemacs.  I was unable to reproduce this behavior in a clean Emacs 26.3 config with current versions of all packages.

**Comment by alphapapa** [comment]
Out of curiosity, I tested a new, clean Spacemacs installation and was also unable to reproduce this problem.  

There must be something wrong with your config.  Try with a clean Spacemacs installation.
