### ISSUE TITLE
Ubuntu issues

### ISSUE THREAD

**Issue by wow-yorick** [alphapapa/magit-todos#89]
my emacs version is 26.2
when i use dired-mode to select file , the first times it warn  ' apply: Selecting deleted buffer' then  second action its ok

i use `RET` call  `(dired-find-file)`  appear this  thing

![image](https://user-images.githubusercontent.com/3367220/68986973-addbcd00-085f-11ea-953a-3b411e27110c.png)

**Comment by alphapapa** [comment]
What does this have to do with magit-todos?

**Comment by wow-yorick** [comment]
sory， i don't describe clearly that issue
this is my config
```
(when emacs/>=25.2p
  (use-package magit-todos
    :hook (emacs-startup . magit-todos-mode)))
```

if i remove ~ :hook (emacs-startup . magit-todos-mode)~ its  resolved

**Comment by alphapapa** [comment]
Unfortunately, there are many variables at play.  I can't reproduce this problem on my config.  You will have to investigate further.  I recommend using `emacs -q` and producing a minimal list of steps that reproduce the problem.  You should also list the versions and sources of all relevant software.

**Comment by muihlinn** [comment]
> if i remove ~ :hook (emacs-startup . magit-todos-mode)~ its resolved

Although I haven't experienced this exactly I've had troubles with a couple of packages using `use-package`'s `:hook` before; more than probably my fault, but I'm a mere mortal who doesn't have the time to investigate everything that doesn't work the way I understand its documentation. ;-)

I "solved" many of those issues including an encapsulated `use-package` declaration into `:config` clause of the package it's supposed to hook on when the required package.

something like this:
```
(use-package magit
  :ensure t
  :config  
	       (use-package magit-todos
		  :ensure t
		  :config (magit-todos-mode)))
``` 
hope it may help you.

**Comment by wow-yorick** [comment]
@muihlinn Thank you very much！  its very good

**Comment by alphapapa** [comment]
@muihlinn Thanks for sharing that.

Looking at the macro expansion for the following code, this is probably a safe and reasonably "correct" way to load and configure this package without forcing itself and Magit to be loaded at Emacs startup:
```el
(use-package magit-todos
  :after magit
  :config (magit-todos-mode))
```
I think the effect of that will practically be the same as the nested `use-package` forms, but some people may prefer not to nest them.

@wow-yorick If possible, please let me know if that code works properly for you and I may add it to the documentation as the officially recommended configuration.

**Comment by muihlinn** [comment]
@alphapapa makes sense as `:config` is executed only once the package is loaded.

As rule of thumb I do nesting when the configuration needed is minimal **and** the package is only going to be used with the "peer",  favouring having *"everything in a place"* and readability. If configuration grows I pull it out as the gains pointed above are lost .

**Comment by wow-yorick** [comment]
@alphapapa  ok  I haven't try it now ，i will try it , if it work, i will tell you the result

**Comment by wow-yorick** [comment]
@alphapapa  i had try it ,   that code works properly for me
