### ISSUE TITLE
magit-todos-branch-list-commit-ref feature request

### ISSUE THREAD

**Issue by mpanarin** [alphapapa/magit-todos#91]
First of all, big thanks for the package that I use everyday and that is extremely usefull.

Currently, I work on a huge project that has approximately a thousand TODOs from different people in the project. And with that amount of them it becomes less and less usefull.

The feature of branch TODOs are awesome, but a bit lacking.

My idea is to allow user defining a function to obtain the `magit-todos-branch-list-commit-ref`.
For example I want to get TODOs that I created in this branch, that is several commits long.
In this case, I need to pass a common ancestor(with `git merge-base`) of master and my branch to get proper commits in diff. 

It seems that it will require some changes to `magit-todos-defscanner` in order to allow subcommands and threading their results to the final command

**Comment by alphapapa** [comment]
Hi,

Thanks for the kind words.  I'm glad it's useful to you.

That is indeed a lot of todos!

> In this case, I need to pass a common ancestor(with git merge-base) of master and my branch to get proper commits in diff.

Aha!  `git merge-base` sounds like the solution I wasn't able to find!  I've never been happy that the branch diff only shows TODOs from HEAD, but I couldn't find a way to do The Right Thing without writing custom code to process the diff of each commit manually.

Is there any reason to not simply use `git merge-base` to get the commit ref for the branch scanner in all cases?  I guess I'll have to do some testing, but maybe you know more about it than I do.

Thanks.

**Comment by alphapapa** [comment]
For example, in a quick test, this seems to properly show all TODOs from the current branch in the branch TODOs list, rather than only those from the HEAD commit:

```el
(magit-todos-defscanner "git diff"
  ;; NOTE: This scanner implements the regexp *searching* in elisp rather than in the
  ;; external process because, unlike "git grep", "git diff" does not support PCRE.
  :test t
  :command (progn
             ;; Silence byte-compiler warnings about these vars we don't use in this scanner.
             (ignore search-regexp-elisp search-regexp-pcre extra-args directory depth)
             (list "git" "--no-pager" "diff" "--no-color" "-U0"
                   (string-trim (shell-command-to-string "git merge-base HEAD master"))))
  :callback 'magit-todos--git-diff-callback)
```

**Comment by alphapapa** [comment]
Example:
![todos](https://user-images.githubusercontent.com/601365/70407971-1572db80-1a0c-11ea-9bcc-794adbcb0ed8.png)

**Comment by mpanarin** [comment]
> Is there any reason to not simply use `git merge-base` to get the commit ref for the branch scanner in all cases? I guess I'll have to do some testing, but maybe you know more about it than I do.

No, not really. First thing i thought of is backwards compat and user experience on the change. But to be honest, I think it is an improvement overall.

One thing to note though is the `HEAD^` approach is branch agnostic, while `merge-base` requires a base branch. So, it is worth making the branch customizable and available to be changed through `dir-locals` (in case it requires some additional setups, which i don't know of)

**Comment by alphapapa** [comment]
If I understand correctly, that would matter in the case of a graph like:
```
---A1---A2---A3 (master)
    \
     B1---B2---B3 (topic)
           \
            C1---C2---C3 (topic2, HEAD)
```
Where branch `topic2` is branched from branch `topic` rather than from `master`, and it would cause TODOs from `B1` and `B2` to be displayed rather than only ones from `C1-C3`.  Right?

Do you know of a simple way to detect that `topic2` is branched from `topic`?  There must be a git command for that.  It would be nice to do it automatically.  I looked at `git merge-base` and `git show-branch`, but neither of those seems to do it (though I may have missed something among the options).

Thanks for your help with this.

**Comment by alphapapa** [comment]
From a quick search, I found this: https://stackoverflow.com/questions/3161204/how-to-find-the-nearest-parent-of-a-git-branch  It doesn't appear to be as simple as I thought.  I'd prefer to avoid having to call a command with several pipes, or parse the multi-line output of a git command, but maybe that's the only way.

**Comment by mpanarin** [comment]
There is no such a way, as it is not by git philosophy )
`topic 2` is *branched from* master just as topic. Branches in git are a simple label on a commit and has no connection to the actual structure )

**Comment by mpanarin** [comment]
I think we should just allow specifying the target branch instead of trying to guess. Because:
1. This basically means we should check against all branches
2. I don't think it provides any real benefit in the end. Projects generally branch out from 1 specific branch. In rare cases when you need to show TODOs from a different comparison, we should allow specifying such a branch locally

imo, of course

**Comment by mpanarin** [comment]
So, I've got an idea:
1. Make a custom var for the default base branch for project (probably master by default)
2. Add an interactive function that allows us to specify different target branch
3. in the magit status buffer show this block as TODOs (Branch from **basebranch**)
4. Make a bind that will call interactively the function to change base branch

The only thing I am not sure though is how to make it persistent for branches. In order to avoid specifying it again and again. Magit caches some branch parameters somewhere, can we mess with that? Something like advising its cache function to include our values as well?

**Comment by alphapapa** [comment]
I think that should do it.  Please let me know what you think.  Thanks for your advice on this.

**Comment by alphapapa** [comment]
Well, I forgot about your other ideas.  :)  Let me work on those too...

**Comment by alphapapa** [comment]
Ok, I think that should do it.  Let me know what you think.

**Comment by mpanarin** [comment]
@alphapapa I tested this for a while and it is pretty good! Huge thank you for the changes!

few things to mention:
1. Would be nice to have an option that disables all todo-items, leaving only the branch ones.
2. https://github.com/alphapapa/magit-todos/blob/master/magit-todos.el#L682 should probably be `magit-todos-branch-list-merge-base-ref` instead of `"master"`
3. https://github.com/alphapapa/magit-todos/blob/master/magit-todos.el#L405 this *kind of* works.
As it is local var it will be dropped as soon as you close the status buffer (in evil it is as simple as pressing `q`). So you'll have to set it every time you open status. 
That's what I meant by:
> The only thing I am not sure though is how to make it persistent for branches. In order to avoid specifying it again and again. Magit caches some branch parameters somewhere, can we mess with that? Something like advising its cache function to include our values as well?

Is there a way to cache something like an alist (branch_name . base_branch_name) and use that to determine the ref? And leave `magit-todos-branch-list-merge-base-ref` as a kind of default?
This way it can be persistent and won't require a lot of manual changes to `magit-todos-branch-list-merge-base-ref`

**Comment by alphapapa** [comment]
> @alphapapa I tested this for a while and it is pretty good! Huge thank you for the changes!

You're welcome!

> 1. Would be nice to have an option that disables all todo-items, leaving only the branch ones.

You can set `magit-todos-update` to nil and the main list will only be updated manually.  Is that enough?  I'd rather avoid adding too many options to control these things.

> 2. https://github.com/alphapapa/magit-todos/blob/master/magit-todos.el#L682 should probably be `magit-todos-branch-list-merge-base-ref` instead of `"master"`

I think it's correct as-is, because the option is still this:
```el
(defcustom magit-todos-branch-list 'branch
  "Show branch diff to-do list.

This can be toggled locally in Magit buffers with command
`magit-todos-branch-list-toggle'."
  :type '(choice (const :tag "Never" nil)
                 (const :tag "In non-master branches" branch)
                 (const :tag "Always" t)))
```
So when that option is `branch`, whether the branch list is displayed is still a matter of whether the current branch is `master`.  The merge-base ref isn't relevant for deciding whether the branch list should be displayed.

> 3. https://github.com/alphapapa/magit-todos/blob/master/magit-todos.el#L405 this _kind of_ works.
>    As it is local var it will be dropped as soon as you close the status buffer (in evil it is as simple as pressing `q`). So you'll have to set it every time you open status.

Yes, it's a buffer-local variable, so it will reset when the status buffer is killed and recreated.  In non-EVIL Emacs, `q` merely buries the buffer rather than kills it, so it's not quite as inconvenient.

>    That's what I meant by:
> 
> > The only thing I am not sure though is how to make it persistent for branches. In order to avoid specifying it again and again. Magit caches some branch parameters somewhere, can we mess with that? Something like advising its cache function to include our values as well?
> 
> Is there a way to cache something like an alist (branch_name . base_branch_name) and use that to determine the ref? And leave `magit-todos-branch-list-merge-base-ref` as a kind of default?
> This way it can be persistent and won't require a lot of manual changes to `magit-todos-branch-list-merge-base-ref`

I'm not aware of a way to cache per-branch settings like that.  If Magit has such a feature, and *if it's intended to be used by other packages*, I'd be willing to support that feature.  Otherwise, it would be either hacky or probably more complicated than it would be worth (I don't want to add such a per-branch key-value cache to this package).

A hacky workaround for long-lived branches (which you could probably copy to other branches) might be to use a dir-local variable to eval code that sets the merge-base-ref variable.

If any further enhancements or fixes are needed, please feel free to open another issue.  Thanks for your help with this.
