### ISSUE TITLE
Update jump-to keybindings for Magit's using Transient now

### ISSUE THREAD

**Issue by atanasj** [alphapapa/magit-todos#95]
I am using [this emacs config](https://github.com/seagle0128/.emacs.d), and it has the following setup for `magit-todos`:

```emacs-lisp
 (use-package magit-todos
   :init
   (setq magit-todos-nice (if (executable-find "nice") t nil))
   (magit-todos-mode 1))))
```

And I have added the following for my own config: 

```emacs-lisp
  (with-eval-after-load 'magit-todos
    ;; add custom hl-todos and set colours
    (add-to-list 'hl-todo-keyword-faces '("ANCHOR" . "#DAF7A6"))
    (add-to-list 'hl-todo-keyword-faces '("REVIEW" . "#5eff33"))
    (add-to-list 'hl-todo-keyword-faces '("NOTE" . "#ff8e33"))
    (add-to-list 'hl-todo-keyword-faces '("TODO" . "#ff3349"))
    (add-to-list 'hl-todo-keyword-faces '("SYNOPSIS" . "#4fd4ff"))
    (setq magit-todos-keywords (list "TODO" "FIXME" "REVIEW"))
    )
```

I get the "Not overriding bind..." error regardless of whether I add my config or not. Additionally, when I do add my config, I get the additional TODOs highlighted, but they are not shown in the `magit` buffer.

What is going wrong?

**Comment by alphapapa** [comment]
It's not an error, it's informative.

If you have problems using someone else's config, please ask them for help with it.

**Comment by mpereira** [comment]
People wanting to suppress the output can use something like the following:
```emacs-lisp
(use-package magit-todos
  :config
  (let ((inhibit-message t))
    (magit-todos-mode 1)))
```

**Comment by alphapapa** [comment]
It seems that recent versions of Magit define the jump-to-section keybinds with Transient, which breaks the `jT` bind this package uses, anyway.  I don't know if it's even possible to reconcile that, since I don't think we can add to its Transient commands.

**Comment by BlindingDark** [comment]
> I don't know if it's even possible to reconcile that, since I don't think we can add to its Transient commands.

https://magit.vc/manual/transient/Modifying-Existing-Transients.html#Modifying-Existing-Transients

```lisp
(transient-append-suffix 'magit-status-jump '(0 0 -1)
  '("T " "Todos" magit-todos-jump-to-todos)))
```

![image](https://user-images.githubusercontent.com/13600799/86554518-6e91f600-bf80-11ea-9f29-1a1607db8cfa.png)

**Comment by BlindingDark** [comment]
Complete workaround example

```
(use-package magit-todos
  :ensure t
  :after (magit)
  :config
  (let ((inhibit-message t))
    (magit-todos-mode 1))
  (transient-append-suffix 'magit-status-jump '(0 0 -1)
    '("T " "Todos" magit-todos-jump-to-todos)))
```

**Comment by alphapapa** [comment]
@BlindingDark Thank you, that looks like a good solution.  I'll see about adding it to this package when I work on it again.
