### ISSUE TITLE
Not working in 25.2

### ISSUE THREAD

**Issue by seagle0128** [alphapapa/magit-todos#96]
In Emacs 25.2.2, I got this error. Should use `-when-let*` or drop 25.x.

```
Symbol's function definition is void: when-let*
```

**Comment by alphapapa** [comment]
Thanks.  How did you notice this?  Are you still using Emacs 25.2 personally?  Which solution do you think I should use?

**Comment by seagle0128** [comment]
I have a testing  env and 25.2.2 is installed by default. I notice `magit-todos` supports 25.1+.
Regarding such compatibility issues, I suggest to use `dash`, or defalias like this. 

```
(unless (fboundp 'when-let*) (defalias 'when-let* #'when-let))
```

**Comment by CsBigDataHub** [comment]
@alphapapa @seagle0128 

Package is also not working for some repositories while it's working for `.emacs.d `repo.

I have a repository with yaml files and `magit-todos-mode` does not show up in `magit-status-buffer` . I get a empty buffer if I run `magit-todos-list`. When I run `ivy-magit-todos`  i  get `nice failed` in mini-buffer .

I have installed `libnice` with `homebrew`.

This is how I have it in yaml file 
![image](https://user-images.githubusercontent.com/23665525/78689697-3e24b800-78bc-11ea-99a4-ca811a47e691.png)

I am using `centaur-emacs` configuration with `emacs 26.3` on macos.

**Comment by alphapapa** [comment]
@CsBigDataHub Why did you post under this issue?  This issue about Emacs 25.2, which you are not using.

**Comment by CsBigDataHub** [comment]
> @CsBigDataHub Why did you post under this issue? This issue about Emacs 25.2, which you are not using.

@alphapapa , I thought this was relevant here. When I was creating a issue, Github suggested this as a relevant issue . Do you want me to create a new issue?

**Comment by alphapapa** [comment]
v1.6 of magit-todos requires Emacs 26.1 or later, so closing this.  Thanks for reporting, though.
