### ISSUE TITLE
Operations that result in refreshing the magit-todos section are very slow on large repositories

### ISSUE THREAD

**Issue by mpereira** [alphapapa/magit-todos#97]
Hi @alphapapa,

I'm working on a fairly large private repository. When opening magit-status, magit-todos blocks and takes around 5 seconds to populate its section. I also noticed that some operations like deleting an untracked file cause the magit-todos section to be refreshed, which presents a similar behavior as above.

I tried setting `magit-todos-update` to `86400`, but that doesn't seem to have an effect. The magit-todos section is refreshed when deleting an untracked files, as well as when closing and reopening magit-status.

Here's a profile of deleting an untracked file in this repository:
[magit-todos-freezing-emacs-when-deleting-untracked-file.txt](https://github.com/alphapapa/magit-todos/files/4388841/magit-todos-freezing-emacs-when-deleting-untracked-file.txt)

Emacs version: 28.0.50

magit-todos version information:
```
;; Package-Version: 20200204.923
;; Version: 1.5.1
```

**Comment by alphapapa** [comment]
It's generally recommended to set `magit-todos-update` to nil in repositories so large that updating is too slow.

**Comment by mpereira** [comment]
> You'll need to be more specific.

I was under the impression that setting `magit-todos-update` to e.g. `60` seconds would cause that no matter what (magit-status buffers opening and closing, magit operations happening under a magit buffer, etc.) the magit-todos section would only (and at most) be refreshed every 60 seconds, but that doesn't seem to be the case. Even with `magit-todos-update` set to `60`, re-opening a magit-status buffer will cause the magit-todos section to be refreshed, regardless of the last time it was refreshed. I think that may be because the variable is buffer-local. Would it make sense for it to be "git-repository-local"?

> It would be helpful if you provided information such as which scanner you're using, how big the repo is, how many to-do items are found, etc.

The scanner is `magit-todos--scan-with-rg`.

This is the total size of the repository, obtained with [loc](https://github.com/cgag/loc):
```
 Language             Files        Lines        Blank      Comment         Code
--------------------------------------------------------------------------------
 Total                15098      2733311       345428       293374      2094509
```

1100 TODOs are found.

> It's generally recommended to set magit-todos-update to nil in repositories so large that updating is too slow. If there are many thousands of tasks (e.g. like in the emacs.git repo), it's going to take time for Emacs to process them

Yep, that's what I did for now.

**Comment by alphapapa** [comment]
> I was under the impression that setting magit-todos-update to e.g. 60 seconds would cause that no matter what (magit-status buffers opening and closing, magit operations happening under a magit buffer, etc.) the magit-todos section would only (and at most) be refreshed every 60 seconds, but that doesn't seem to be the case. 

The cache is a buffer-local variable.  If you kill a magit-status buffer, the cache for that repo is cleared.

> Even with magit-todos-update set to 60, re-opening a magit-status buffer will cause the magit-todos section to be refreshed, regardless of the last time it was refreshed. I think that may be because the variable is buffer-local. 

I'm not sure exactly what you mean by "re-opening a magit-status buffer".  Please be very specific about the steps you are taking.

> Would it make sense for it to be "git-repository-local"?

Probably not, because there is no mechanism for caching data that way.  I recommend simply not killing magit-status buffers while you're still working on a project.  The magit-status buffer itself takes a trivial amount of memory.

> 1100 TODOs are found.

That will take a while, because Emacs has to parse the output of `rg` and insert 1100 `magit-section`s for all the task items.  Maybe the Emacs 28 native-comp branch will help.  But if you use caching and don't kill the status buffers, it will probably be good enough.

**Comment by mpereira** [comment]
> I'm not sure exactly what you mean by "re-opening a magit-status buffer". Please be very specific about the steps you are taking.

1. Open magit-status buffer: calling `M-x magit-status`. magit-todos section is refreshed
2. Close magit-status buffer: pressing `q`, which invokes `magit-mode-bury-buffer`. magit-status buffer is buried, not killed
3. Re-opening magit-status buffer: calling `M-x magit-status`. magit-todos section is refreshed, regardless of `magit-todos-update`

**Comment by mpereira** [comment]
As it can be seen in the profiler report I attached in the first message, magit runs `magit-status-sections-hook` hooks after some operations (deleting an untracked file is one, and I'm assuming the `M-x magit-status` in step 3 above to be another) via `magit-refresh`, which calls `magit-todos--insert-todos`.

**Comment by alphapapa** [comment]
> As it can be seen in the profiler report I attached in the first message, magit runs `magit-status-sections-hook` hooks after some operations (deleting an untracked file is one, and I'm assuming the `M-x magit-status` in step 3 above to be another) via `magit-refresh`, 

A profiler report isn't very relevant here, as the issue seems to be that the value of `magit-todos-update` does not seem to be having the expected effect.  A backtrace would be more appropriate, but also probably unnecesary.

> which calls `magit-todos--insert-todos`.

That function does not unconditionally re-scan for items; it depends on the value of `magit-todos-update`.

AFAIK there are no bugs regarding `magit-todos-update` being respected (not that there couldn't be any), so I wonder how you are setting that variable.  Please be very specific.

**Comment by mpereira** [comment]
> AFAIK there are no bugs regarding magit-todos-update being respected (not that there couldn't be any), so I wonder how you are setting that variable. Please be very specific.

This is my magit-todos snippet simplified:
```
(use-package magit-todos
  :ensure nil
  :quelpa (magit-todos
           :fetcher github
           :repo "alphapapa/magit-todos")
  :after magit
  :config
  (let ((inhibit-message t))
    (magit-todos-mode 1))
  (setq magit-todos-update 86400))
```

`M-x describe-variable`
```
magit-todos-update is a variable defined in magit-todos.el.

Value
86400

Original Value
t

...
```

**Comment by alphapapa** [comment]
Please note that using `setq` to set `defcustom`s can result in incorrect behavior.  In this case it's okay, but if a `defcustom` has a setter, it won't work properly.  This has been the cause of several false bug reports on this package.  Instead, use the `use-package` `:custom` keyword, which is correct (and more concise, anyway).

I used your code in a clean Emacs configuration, testing it with the emacs.git repo, and I could not reproduce a problem.  The caching works correctly, and there are 1,970 TODOs listed.  So I looked at the profiler report you attached, and everything appears to be in order: it appears to indicate that the cached items are being inserted.  It simply takes a while to insert that many sections into a buffer, and magit-status buffers work by re-inserting all contents when it is refreshed.

So there does not appear to be a bug here.  If even inserting cached items is too slow for you on such large repos, you should probably not use magit-todos on them until you need to.

**Comment by mpereira** [comment]
I appreciate your time looking into this, thank you.

> it appears to indicate that the cached items are being inserted. It simply takes a while to insert that many sections into a buffer, and magit-status buffers work by re-inserting all contents when it is refreshed.

So the magit-status buffer's magit-todos entries are re-inserted even when cached? Would it make sense to not re-insert cached items on magit-status buffer refreshes?

**Comment by mpereira** [comment]
> you should probably not use magit-todos on them until you need to. You might use magit-todos-list instead of magit-todos-mode on them.

👍

**Comment by alphapapa** [comment]
> Would it make sense to not re-insert cached items on magit-status buffer refreshes?

As I said, magit-status buffers work by re-inserting all contents when the buffer is refreshed.  If the items were not re-inserted, they would not be present in the buffer, which would be equivalent to disabling `magit-todos-mode`.

**Comment by mpereira** [comment]
I see. Thanks for clarifying, and feel free to close this issue!
