### ISSUE TITLE
Problem with magit-todos--scan-with-git-diff

### ISSUE THREAD

**Issue by mclearc** [alphapapa/magit-todos#99]
I recently switched to straight as my package manager. Now, when running magit status in my .emacs.d directory `magit-todos--scan-with-git-diff` pins my emacs cpu usage at 100%. Going to the diff buffer reveals that the scan is reading the addition of straight and the deletion of my old package directory. I've got something like 300 packages so it's a very large diff scan! I've tried excluding any such scan using a dir-local variable like so (note ".local" contains my straight directory):

```
((magit-status-mode
  (magit-todos-exclude-globs ".local/")))
```

But this doesn't seem to do anything. Any idea what I might be doing wrong? I expect that this is user error and not a bug but help is appreciated, since I use this package to track problem areas in my config. thanks!

**Comment by alphapapa** [comment]
The first thing I notice is that there are no wildcards in that glob string, so that's probably not right.

**Comment by mclearc** [comment]
unfortunately changing to 

```
((magit-status-mode
  (magit-todos-exclude-globs ".local/*")))
```

makes no difference. 

I just had to kill the `magit-todos--scan-with-diff` buffer at 191356 lines and going up rapidly.

**Comment by alphapapa** [comment]
Unfortunately, that option is not applied to the diff scanner, as you can see here: https://github.com/alphapapa/magit-todos/blob/a0e5d1f3c7dfcb4f18c1b0d57f1746a4872df5c6/magit-todos.el#L1292

Looking at `man git diff` again, I don't see a way to exclude files based on glob patterns.

I guess you'll need to reconfigure the diff scanner in that repo.  See `M-x customize-option RET magit-todos-branch-list RET`.

**Comment by mclearc** [comment]
Ah - I see. So that's what the `:ignore ...` means (sorry, my elisp is not ... great). Thanks -- I'll reconfigure as you suggest.

**Comment by mclearc** [comment]
For any others -- `(setq magit-todos-branch-list nil)` fixed the issue for me.

**Comment by alphapapa** [comment]
FYI, there's also a command for that: `add-dir-local-variable`.
